app/cases/controllers/discussionSection.js, app/cases/services/discussionService.js, app/cases/views/discussionSection.jade
@sshumake  Can you please take a look at this. The usual comments are getting sorted but the chat ones are not. Basically interleaving of chats and comments is not happening as expected.
The   "  orderBy:'last_modified_date'  " filter should be working on each object in the " discussionElements " list. But i think the sorting is happening after the chat comments are loaded into the ^ list.
I had implemented this successfully in the old PCM master using angular.sort()  but it was performance centric. If you need to see this in action, below is the data.
Test Data :   User - skesharigit (or probably any other internal)
case_number - 01359622 : environment - QA
case_number - 00531482 / 01152512 : environment - CI
Please let me know if i am missing something.
=> Fix for PCM-328 & PCM-388

app/cases/controllers/addCommentSection.js
@renujhamtani @pbathia 
This is a definite monkey patch but the browser when copying and pasting has a bug where it allows more characters in the text box even though you set a hard limit.  This is as good as it gets for now.
=> Monkey patch

app/assets/sass/components/_case-discussion.scss, app/cases/views/newAlternate.jade
@mattnolting @sshumake Please review the changes for PCM-1046. Was there a better way to do this?
The label "Send Email Notifications to" is not showing up in emailNotifySelect.jade because it cannot find .label. So i have added .label copied from _config-options.scss to _case-discussion.scss. Is this the right way to do this? Can we reuse label instead of duplicating code? I am not sure on how to do that..
=> PCM-1046 changes

app/chromed.html, app/localFile.js
@gandhikeyur @renujhamtani Please Review.
The chromed.html is used locally and thus this dependency will not affect any other environment.
=> PCM-1720 fix for running PCM locally

app/cases/services/searchCaseService.js
This was caused by infinite-scroll that kept repeating the request, even though it was failing.
=> PCM-1868: Removed excessive request on 401 response

app/cases/controllers/detailsSection.js, app/cases/controllers/discussionSection.js, app/cases/services/linkifyService.js, app/cases/views/detailsSection.jade, app/chromed.html, app/index.html
@gandhikeyur Please review.
I talked with spenser and we decided that adding some hash symbol to indicate case number reference is unfeasible, due to the number of existing cases and the fact that customers would need to be forced to use it. So we decided to proceed with the regex solution; the priority is to prefer non-highlighted occurrences rather than having false positives. Let me know what you think.
=> PCM-776: Added case number highlight

app/cases/services/caseService.js
@renujhamtani @gandhikeyur Please review.
The product and version components calling this function are used on edit page as well. This check will make sure we don't fire this event from any other page.
=> Adding check for new case url

app/cases/controllers/bookmarkedAccountSelect.js, app/cases/services/searchCaseService.js
@renujhamtani @vrathee @gandhikeyur Please review, this fixes the case-loading blocker
https://projects.engineering.redhat.com/browse/PCM-3350
What happens in PCM is that if the request for cases (/case/filter with SSO in the payload) fails, PCM runs another query, this time without the SSO. The one line in `searchCaseService.js` prevented the other request form being executed. Not sure why two requests need to be executed, or why the first one fails. Strata team should still investigate why the first requests fails with 404.
=> PCM-3350: Fix for cases not being fetched

app/cases/controllers/advancedSearchController.js, app/cases/controllers/manageGroups.js
@renujhamtani While fixing this I noticed there are two routes we probably don't use anywhere. Both `editGroup` and `defaultGroup` routes seem to have been replaced by the manage groups interface. Should I remove those routes?
=> PCM-3339: Fixed breadcrumbs for Search and Groups

app/cases/views/edit.jade, app/cases/views/new.jade
@gandhikeyur (@engineersamuel) Please review.
A bit of background on why is this needed, previously, we got the authentication cookie (rh_sso) right out of SSO when logging in, currently we get the cookie (rh_jwt) when the session.js initializes. So, we need to delay ALL the calls to strata until that is done. On edit and new case views, some requests were firing even before that, because some components perform their init independent on the authentication, so I just replaced `ng-show` with `ng-if` to make sure the components are initialized only after auth succeeds.
=> PCM-3257: Fixing init behavior

app/cases/controllers/advancedSearchController.js
https://projects.engineering.redhat.com/browse/PCM-3609
The `absolute: true` generated absolute URL without the proper path. To fix this, I removed generate relative url, and let browser handle the conversion to absolute. Opening in a new tab and copying with right-click still works fine.
=> PCM-3609: Fixing public search link

app/cases/views/discussionSection.jade, package.json
@vrathee @gandhikeyur @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-3632
From my limited knowledge of translations, I put together a new way to generate translation templates. Instead of grunt I use angular-gettext-cli, and the generation is done in two parts:
- scraping the dist .js file
- srcaping the view files
Since we no longer generate .html, and since the angular-gettext-cli doesn't understand .jade, I had to add a compilation from jade to html as well. Please, think about this PR and ask questions if something doesn't feel right.
To build the templates you need to install **angular-gettext-cli** with `npm install -g angular-gettext-cli`, **jade** with  `npm install -g jade` and **msgcat** (that was bundled with my fedora already).
Then the …
=> Fixing translations

app/chromed.ejs
As a short-term fix for the require.js caching we've been seeing, I am adding a random ?v param to the url. This prevents from using too old version of that file. Note we have already applied this as a hotfix to prod, but we also need this in the codebase.
=> PCM-3783: Adding random hash to require.js

app/cases/controllers/emailNotifySelect.js
@vrathee @gandhikeyur Please review. If an internal watcher is already selected, we don't want to show that user in the search.
https://projects.engineering.redhat.com/browse/PCM-3954
=> PCM-3954: Not showing already selected internal watchers

app/loader.js, app/main.module.js
@jtrantin @renujhamtani Please review.. This fixes the console error we get if strata returns a 404 for account..
=> Removing the console error that pops up if strata response for account is empty

app/cases/services/caseService.js
@vrathee @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-4356
The problem here is we fetch RH users only from account 540155 while there are many RH accounts. This prevented users from using the "Add me as watcher" button. To quickly workaround the problem, I am always adding `authedUser` to the RH users list if he's internal.
=> PCM-4356: Adding internal authedUser to RH users list

app/cases/services/caseService.js
https://projects.engineering.redhat.com/browse/PCM-4424
IMO there is no need to reset `CaseService.groups` in `clearCase`, because those are case groups of the authedUser and thus are not dependent on a case.
=> PCM-4424: Not resetting groups when a case is opened

app/cases/views/detailsSection.jade
@renujhamtani @jtrantin please review.
I forgot to add the maxlength on edit page. Adding this will help to avoid the error message.
=> PCM-4436: add maxlength 255 to hostname field in edit page to avoid error message

app/cases/controllers/new.js, app/cases/views/accountSelect.jade, app/cases/views/new.jade
@gandhikeyur Please review.
Surprisingly, the existing components ca be reused to full extent, I only changed when they are shown. Tested with internal/external org-admin/non-org-admin and all seems to be working fine.
=> PCM-4466: Let external org-admins create case on their managed accounts

app/cases/views/detailsSection.jade
@renujhamtani Merging this as this is needed for Monday secure support release and the sbr changes are not working as expected, hence I have to again disable this field in QA.
=> Making sbr readonly and visible only if its linked to a secure support cases

app/cases/controllers/new.js, app/cases/services/caseService.js
@engineersamuel @vrathee @kunyan @renujhamtani  Please review.
https://projects.engineering.redhat.com/browse/PCM-5052 
As of now, I have hardcoded a few lines to manually put a new case object in the localStorage cache for testing.
**Note :** I would be removing it in once the solution engine or container catalog are ready with their changes.
The flow would be as furnished below:
1) Solution engine & Container Catalog to store case creation details in local storage and pass the local storage key as the paramter in the new case url like https://access.qa.redhat.com/support/cases/#/case/new?caseCreateKey=cc-123456
2) PCM to read this caseCreateKey and fetch the stringified object from localStorage cache, parse it to get actual JSON object and fill the details in the respective fields on …
=> PCM 5052 : reading object from url and filling new case fields

app/cases/views/list.jade
@renujhamtani Merging this.
As per the discussion in the jira PCM-5159 , opening solution engine in the same tab as that of PCM when the user clicks on Solution engine hyperlink on case list page.
=> PCM 5159 opening solution engine in the same tab as that of PCM

app/assets/sass/components/_case-discussion.scss, app/cases/controllers/emailNotifySelect.js, app/cases/controllers/new.js, app/cases/views/detailsSection.jade, app/cases/views/edit.jade, app/cases/views/emailNotifySelect.jade, app/cases/views/new.jade
@renujhamtani @kunyan @engineersamuel @vrathee Please review.
Code changes for https://projects.engineering.redhat.com/browse/PCM-4681 
As angular chosen was misbehaving and not allowing to properly use its disabled property for the version that we are using in PCM, I have used a disabled text input with palaceholder in the new case page. In the case edit page, I have used a div with exact borders and labels inside it to replicate the behaviour of a disabled chosen.
Also, the issue of not sending email notification fields for internal and external org admins are fixed in this PR.
Please let me know in case of any queries. I think this is an important jira that needs to be pushed in the upcoming production release, please review as soon as possible.
=> PCM 4681 code changes

app/main.module.js
@renujhamtani @engineersamuel @anujsi Please review.
Made these changes as per the mail by pcon, that the stage url is not https and hence the chat functionality is not working in PCM stage.
This can be merged as this functionality is only limited till stage environment.
=> Stage Chat window fix : Using https in the chatIframeHackUrlPrefix

app/cases/services/productsService.js
@anujsi @aksgupta14 @kunyan Please review.
Removing preferred service level as we do not want the UI to auto select an entitlement if the product is not supported.
https://projects.engineering.redhat.com/browse/PCM-6621
=> pcm-6621 - removing auto select for unsupported products

app/cases/services/attachmentsService.js
@vrathee @anujsi @jeudy100 Please review
While debugging with najain, we observed that the s3 config calls were getting executed even before the init of the app and hence the cookies were not getting parsed in the Api call which resulted in 401 errors randomly for s3 configs.
Having s3 config result is much needed for the new uploader functionality to work.
I did not have a jira number handy, hence I have not tagged any jira in this PR.
=> Fixing 401 error call for s3config, executing call after init success

app/assets/sass/components/_case-discussion.scss
Recently we have changed our base font family to 'Red Hat Text' from 'Overpass' while doing that we have also changed the default font family of pre and form elements to  'Red Hat Text' from 'monospace' font hence the alignment of texts (specifically logs) were broken.
=> PCM-8633 - In support cases, set both comments and input text box to fixed-width font

app/cases/controllers/productSelect.js, app/cases/views/detailsSection.jade
@vrathee @anujsi Please review.
We will show cluster id on details page if it is present in case details response even if selected product is not Openshift Online.But if product is not openshift online and no cluster id is set we will not show it. This is how SFDC is doing it and Eric Rich suggested doing it the same way in PCM.
=> show cluster id on details page if present in response irrespective of product selected
