redhataccess/redhat_access_angular_ui

app/cases/controllers/list.js, app/cases/services/caseService.js, app/cases/services/searchCaseService.js, app/cases/views/list.jade, app/i18n/template.pot, test/spec/cases/cases.services.test.js
@ardasgup @sshumake  Please review and merge.
=> Changes for PCM 349

app/cases/views/detailsSection.jade
@ardasgup @pbathia Please review this. As this is a simple change, if you two review, I can merge this ASAP.
=> Changes for PCM - 420

app/cases/views/new.jade
@ardasgup @sshumake Please review and merge. A very simple change.
=> Changes for PCM - 421

app/cases/views/commentsSection.jade
@pbathia @renujhamtani Please review/merge.  Very simple change.
=> PCM-341 Request Management Escalation button color change request

app/cases/controllers/list.js, app/cases/services/searchCaseService.js
@ardasgup @renujhamtani Please review
=> pcm-379 Problems with case list

app/cases/controllers/addCommentSection.js, app/cases/controllers/commentsSection.js, app/cases/directives/commentsSection.js
@ardasgup @sshumake  Please review and merge.
=> Changes for PCM-407

app/cases/controllers/new.js, app/cases/views/new.jade, app/cases/views/newRecommendationsSection.jade, app/i18n/template.pot
@ardasgup Please review. 
@sshumake Please review. Should we wait for merge until we get response from Matt ?
=> Changes for PCM - 243

app/cases/cases.module.js, app/cases/controllers/compactCaseList.js, app/cases/controllers/group.js, app/cases/controllers/list.js, app/cases/controllers/search.js, app/cases/services/caseService.js, app/cases/services/searchBoxService.js
https://projects.engineering.redhat.com/browse/PCM-438
=> Case list eventing

app/cases/controllers/defaultGroup.js, app/cases/controllers/requestManagementEscalationModal.js, app/cases/views/defaultGroup.jade, app/cases/views/group.jade, app/security/services/securityService.js
@ardasgup @renujhamtani  Please review
This pull request includes the following Jiras. PCM-441, PCM-442, PCM-443, PCM-444
I realize we previously talked about creating a pull request per issue but all these issues were very closely related and shared a lot a code making that a merge nightmare.
=> Pcm442 pcm444

app/cases/views/list.jade, app/cases/views/new.jade
@ardasgup @sshumake Please review and merge.
=> Changes for PCM-392

app/cases/directives/commentsSection.js, app/cases/views/commentsSection.jade
@pbathia @renujhamtani please review
=> IE8 is the worst thing ever

app/cases/views/commentsSection.jade, app/cases/views/new.jade
modified:   app/cases/views/commentsSection.jade
modified:   app/cases/views/new.jade
=> Changes for PCM-445

app/cases/services/caseService.js
This is a critical defect and should probably be hot-fixed in prod.
@sshumake @renujhamtani  please review and do the needful.
=> Fix for PCM-450

app/cases/cases.module.js, app/cases/controllers/edit.js, app/cases/directives/403.js, app/cases/directives/404.js, app/cases/styles/case.css, app/cases/views/403.jade, app/cases/views/404.jade, app/cases/views/edit.jade, app/cases/views/group.jade, app/cases/views/list.jade, app/cases/views/new.jade, app/chromed.html, app/security/services/securityService.js
@ardasgup @renujhamtani please review
=> 403 and 404 errors enabled

Gruntfile.js
@renujhamtani @sshumake Please review and merge.
=> changes for PCM-419

app/cases/views/list.jade
@renujhamtani @pbathia There is faulty logic in my initial commit.
=> Faulty logicc in pcm 210

app/cases/controllers/detailsSection.js
@ardasgup @sshumake  Please review and merge.
=> Changes for PCM-395

app/cases/cases.module.js, app/cases/controllers/detailsSection.js, app/cases/controllers/new.js, app/cases/controllers/ownerSelect.js, app/cases/views/ownerSelect.jade
@sshumake @renujhamtani   please review and merge !
=> Fix for PCM-185 and PCM-186

app/cases/controllers/new.js
@sshumake @renujhamtani please review and merge !
=> Fix for PCM-187

app/cases/controllers/editGroup.js, app/common/services/strataService.js
@sshumake @renujhamtani  pls review and merge !
=> Fix for PCM-402

app/cases/controllers/editGroup.js, app/common/services/strataService.js
@sshumake  @renujhamtani  please review and merge !
=> Fix for PCM-524

app/cases/controllers/edit.js
@sshumake @renujhamtani  pls review and merge!
=> Fix for PCM-536

app/cases/views/requestManagementEscalationModal.jade, app/i18n/template.pot
@sshumake  @ardasgup  Please review and merge. Also i have also made the changes for additional strings for partner escalation in the template.pot file (as it generated this in addition to my changes).  . We can take the translations defect for newly added string to add these for different languages.
=> Changes for PCM-428

app/cases/services/attachmentsService.js
I will revert this back once tested on CI..so merging this without review as it has to be reverted back.
=> Revert this back to test on CI

app/cases/services/attachmentsService.js
Reverts redhataccess/redhat_access_angular_ui#141
=> Revert "Revert this back to test on CI"

app/cases/services/attachmentsService.js
If everything is good...no revert...but get it reviewed from Aritro and Spenser
=> PCM-427 Test on CI

app/cases/services/attachmentsService.js
Reverts redhataccess/redhat_access_angular_ui#144
=> Revert "PCM-427 Test on CI"

app/cases/services/attachmentsService.js
@ardasgup @sshumake Please review this.  Took so much time to test and figure out that this was just a space issue:( Translation defects are bad:(
=> PCM-427 changes

app/chromed.html, app/loader.js
@ardasgup @renujhamtani  I am verifying and merging since this should never make it out of dev.  Please review and let me know if you see any problems.
=> Fix chroming errors

app/cases/views/attachmentsSection.jade, app/cases/views/new.jade, app/chromed.html
IE attachments was causing the load cases page to be reloading, this was messing up reporting
=> fix loading list page bug

app/index.html
@ardasgup @pbathia  Please review. I will merge once this reviewed. This PR was to add some missing controllers and directives in index.html. Although we need to always test it through chromed.html, sometimes it is easy to first develop on unchromed version and then test on chromed version. Hence pushing this file.
=> Addition of directives/controllers in index.html

.gitignore, Gruntfile.js, app/ascension/ascension.module.js, app/ascension/controllers/caseQueue.js, app/ascension/directives/caseQueue.js, app/ascension/services/caseQueueService.js, app/ascension/views/caseQueue.jade, app/chromed.html, app/index.html, app/redhat_access_module.js
@sshumake @renujhamtani  please review, have not added any routing for internal users since we are not yet ready to do that. But accessing #/ascension would take us to a dumy ascension page i added. We can overwrite the files after this.
=> PCM-609 setting up ascension module

app/cases/controllers/editGroup.js, app/common/services/strataService.js
@renujhamtani pls review and merge.
=> Fix for PCM-619 & PCM-622

app/cases/controllers/detailsSection.js, app/cases/controllers/new.js, app/cases/services/productsService.js
=> Fix for PCM-624 & PCM-625

Gruntfile.js, app/ascension/controllers/caseQueue.js, app/ascension/services/caseQueueService.js, app/chromed.html, app/common/services/udsService.js, app/index.html, app/loader.js, bower.json, karma.conf.js
modified:   Gruntfile.js
modified:   app/ascension/controllers/caseQueue.js
modified:   app/ascension/services/caseQueueService.js
modified:   app/chromed.html
new file:   app/common/services/udsService.js
modified:   app/index.html
modified:   app/loader.js
modified:   bower.json
modified:   karma.conf.js
=> changes for adding provision for making call to UDS via udsjs

app/cases/controllers/addCommentSection.js, app/cases/controllers/detailsSection.js, app/cases/controllers/discussionSection.js, app/cases/controllers/list.js, app/cases/controllers/new.js, app/cases/services/discussionService.js, app/cases/services/productsService.js, app/cases/services/recommendationsService.js, app/cases/services/searchCaseService.js, app/common/controllers/403.js, app/common/controllers/404.js, app/common/controllers/alert.js, app/common/controllers/header.js, app/common/directives/alert.js, app/common/directives/header.js, app/common/directives/titleTemplate.js
modified:   app/cases/controllers/discussionSection.js
=> changes for pcm-507, code quality,declare variable before usage

app/ascension/controllers/accountInfo.js, app/ascension/controllers/breachInformation.js, app/ascension/controllers/caseQueue.js, app/ascension/controllers/entitlementInfo.js, app/ascension/controllers/internalCaseDescription.js, app/ascension/controllers/internalCaseDetails.js, app/ascension/controllers/internalCaseDiscussion.js, app/ascension/controllers/ownerInfo.js, app/ascension/controllers/topCases.js, app/ascension/directives/accountInfo.js, app/ascension/directives/breachInformation.js, app/ascension/directives/entitlementInfo.js, app/ascension/directives/internalCaseDescription.js, app/ascension/directives/internalCaseDetails.js, app/ascension/directives/internalCaseDiscussion.js, app/ascension/directives/ownerInfo.js, app/ascension/directives/topCases.js, app/ascension/views/accountInfo.jade, app/ascension/views/breachInformation.jade, app/ascension/views/caseQueue.jade, app/ascension/views/entitlementInfo.jade, app/ascension/views/internalCaseDescription.jade, app/ascension/views/internalCaseDetails.jade, app/ascension/views/internalCaseDiscussion.jade, app/ascension/views/ownerInfo.jade, app/ascension/views/topCases.jade, app/chromed.html, app/index.html
@mattnolting @sshumake @pbathia Please review and let me know the comments.
The topCases.jade ( final output is not looking good ). Please suggest some changes. I am using Leslie's mockup designs[1]
[1] https://mojo.redhat.com/docs/DOC-1019239?et=notification.mention#comment-990568
=> PCM-610 Initial MockUp

karma.conf.js, test/mocks/mockStrataService.js, test/spec/cases/cases.services.test.js
@sshumake @renujhamtani pls review and merge
=> Fix for PCM-645 unit tests Services

app/ascension/controllers/caseQueue.js
=> Changing event listener on $rootScope to $scope

test/mocks/mockStrataService.js, test/spec/cases/cases.controllers.test.js, test/spec/cases/cases.directives.test.js, test/spec/cases/cases.filters.test.js
@ardasgup @sshumake  I have made the changes to controllers so that they are now passing. Some were not applicable(as the corresponding controller were removed), so deleted the test cases. Also added some for detailsSection controller.
Took the latest from Aritor's fix for services and could see directives failing. I had added xit for those to ignore for now. (there was no easy fix for those as the div tags were completely changed).  We can take this activity once we try to improve the code coverage.
=> PCM-646 Controllers test case fix and minor changes for directives.

app/ascension/controllers/accountInfo.js, app/ascension/controllers/breachInformation.js, app/ascension/controllers/entitlementInfo.js, app/ascension/controllers/internalCaseDescription.js, app/ascension/controllers/internalCaseDetails.js, app/ascension/controllers/internalCaseDiscussion.js, app/ascension/controllers/ownerInfo.js, app/ascension/controllers/topCases.js, app/ascension/directives/accountInfo.js, app/ascension/directives/breachInformation.js, app/ascension/directives/entitlementInfo.js, app/ascension/directives/internalCaseDescription.js, app/ascension/directives/internalCaseDetails.js, app/ascension/directives/internalCaseDiscussion.js, app/ascension/directives/ownerInfo.js, app/ascension/directives/topCases.js
@renujhamtani pls merge this just module name correction!
=> Changing the incorrect module name to ascension

app/cases/controllers/confirmCaseCloseModal.js, app/cases/controllers/detailsSection.js, app/cases/controllers/discussionSection.js, app/cases/controllers/edit.js, app/cases/controllers/list.js, app/cases/controllers/new.js, app/cases/controllers/requestManagementEscalationModal.js, app/cases/services/caseService.js, app/cases/services/productsService.js, app/cases/services/searchCaseService.js, app/common/directives/autoFocus.js
@ardasgup @pbathia Please review these jshint error fixes.
=> JSHINT error fixes

app/cases/views/descriptionSection.jade, app/cases/views/new.jade, app/cases/views/proceedWithoutAttachModal.jade
modified:   app/cases/views/descriptionSection.jade
modified:   app/cases/views/new.jade
modified:   app/cases/views/proceedWithoutAttachModal.jade
=> adding id attribute for test automation

app/cases/controllers/discussionSection.js, app/cases/views/discussionSection.jade
@renujhamtani @pbathia Pls review and merge !
=> Fix for PCM-666

app/cases/controllers/addCommentSection.js, app/cases/controllers/discussionSection.js, app/cases/views/addCommentSection.jade, app/cases/views/discussionSection.jade, app/cases/views/edit.jade
@ardasgup @sshumake Please review and merge
=> changes for pcm-678

app/cases/controllers/attachLocalFile.js, app/cases/services/attachmentsService.js, app/common/services/strataService.js
@sshumake @pbathia pls review and merge !
@sshumake once you merge the stratajs change , i will bump that, because this commit is dependent on that.
=> Fix for PCM-422

app/cases/views/new.jade
=> Fix for PCM-600

app/cases/services/searchBoxService.js, app/cases/views/list.jade, app/cases/views/searchBox.jade
=> Fix for PCM-675

app/cases/controllers/emailNotifySelect.js, app/cases/services/caseService.js
@ardasgup @sshumake Please review and merge
=> PCM-247 changes

app/cases/controllers/detailsSection.js, app/cases/views/detailsSection.jade
=> Fix for PCM-664

app/cases/controllers/new.js
modified:   app/cases/controllers/new.js
=> changes for pcm-862

app/cases/controllers/confirmCaseCloseModal.js, app/cases/services/searchCaseService.js
@ardasgup @sshumake Please review and merge
=> PCM-602 changes

app/cases/controllers/new.js, app/cases/views/newAlternate.jade, app/cases/views/newBase.jade
=> ie file attach

app/cases/views/discussionSection.jade
=> Fix for PCM-689

app/cases/controllers/defaultGroup.js, app/cases/controllers/deleteGroupButton.js, app/cases/controllers/editGroup.js, app/cases/controllers/new.js, app/cases/services/attachmentsService.js, app/common/controllers/header.js, app/escalation/services/escalationRequestService.js
=> Fix for PCM-764

app/cases/controllers/searchBox.js, app/cases/views/searchBox.jade
=> PCM-854 changes

app/cases/controllers/detailsSection.js
=> Fix for PCM-860

app/cases/controllers/new.js, app/cases/services/caseService.js
@ardasgup @pbathia Please review.
=> PCM-839 changes

app/cases/directives/chosenPlaceholder.js, app/cases/views/emailNotifySelect.jade, app/cases/views/newAlternate.jade, app/chromed.html, app/index.html
@ardasgup @pbathia Please review and merge.
=> PCM-861 changes

app/cases/views/addCommentSection.jade, app/cases/views/newAlternate.jade, app/cases/views/newBase.jade
@ardasgup @pbathia Please review.
I am hiding the cancel button and have added this acceptance criteria on JIRA for PCM-631
=> PCM-631 changes

app/cases/views/newAlternate.jade
@ardasgup @pbathia Please review and merge.
=> PCM-890 changes

app/cases/views/addCommentSection.jade
=> PCM-896 changes

app/cases/controllers/attachLocalFile.js
=> PCM-908 changes

app/cases/views/edit.jade, app/common/services/strataService.js
=> PCM-907 changes

app/common/services/strataService.js, app/common/ui-utils.module.js
@ardasgup @pbathia please review
=> PCM-901 changes

app/common/services/strataService.js
=> Fix for PCM-905

app/cases/views/list.jade
=> Fix for PCM-904

app/cases/controllers/discussionSection.js
@ardasgup @sshumake Please review and merge.
=> PCM-695 changes

app/cases/views/detailsSection.jade
@ardasgup @sshumake Please review and merge .
(the anchor tag does not support disabled. We need to use hide for this).
=> PCM-891 changes

app/cases/controllers/addCommentSection.js
=> Fix for PCM-895

app/cases/views/discussionSection.jade
=> PCM-916 changes

app/cases/controllers/detailsSection.js, app/cases/views/detailsSection.jade
=> Fix for PCM-894

test/spec/cases/cases.controllers.test.js
@renujhamtani pls review and merge. This is a current test which was failing.
=> Fix a broken controller test

app/cases/views/confirmCaseCloseModal.jade, app/cases/views/confirmCaseSeverityChangeModal.jade, app/cases/views/confirmCaseStateChangeModal.jade, app/cases/views/proceedWithoutAttachModal.jade
@pbathia @ardasgup Please review
=> PCM-906 changes

app/cases/controllers/filterSelect.js, app/cases/controllers/list.js, app/cases/controllers/listFilter.js, app/cases/services/caseService.js, app/cases/services/searchCaseService.js, app/cases/views/filterSelect.jade, app/cases/views/listFilter.jade, app/chromed.html, app/common/services/constantsService.js, app/index.html
@sshumake @renujhamtani Pls review !
So this commit basically takes into account spenser's search parameters persistence and the 'sort by' localstorage changes.
=> Fix for PCM-342

app/cases/services/attachmentsService.js
@renujhamtani @pbathia This is terrible but "its as good as it gets".  We can talk more in scrum tomorrow if you have any questions.
=> reload in successful upload

app/cases/services/attachmentsService.js
=> fix reload on case create

app/cases/controllers/filterSelect.js, app/cases/controllers/list.js, app/cases/controllers/listFilter.js, app/cases/services/caseService.js, app/cases/services/searchCaseService.js, app/cases/views/filterSelect.jade, app/cases/views/listFilter.jade, app/chromed.html, app/common/services/constantsService.js, app/index.html
@renujhamtani pls merge as i guess this had already been reviewed !
=> Changes for PCM-342

test/mocks/mockStrataService.js, test/spec/cases/cases.controllers.test.js
@ardasgup @pbathia Please review. These are for the failing test cases for PCM- 342 which was merged after the beta prod.
=> Fixing the failing controller test cases

.travis.yml, app/assets/sass/components/_case-list.scss, app/cases/views/list.jade, app/cases/views/newAlternate.jade, app/cases/views/newBase.jade
=> update for connor

app/ascension/controllers/caseDescription.js, app/ascension/controllers/caseDetails.js, app/ascension/controllers/caseView.js, app/ascension/controllers/yourCases.js, app/ascension/services/caseDetailsService.js, app/ascension/views/caseDescription.jade, app/ascension/views/caseDetails.jade, app/ascension/views/yourCases.jade
@sshumake @renujhamtani pls review and merge!
=> Fix for PCM-963

app/ascension/controllers/caseFlags.js, app/ascension/views/caseFlags.jade
@renujhamtani @pbathia please review and merge ! This is an adhoc change as i am not very convinced how the flags would work, have some better ideas, but for now will keep it simple.
=> Fix for PCM-865

app/ascension/ascension.module.js, app/ascension/controllers/caseDiscussion.js, app/ascension/controllers/caseView.js, app/ascension/controllers/yourCases.js, app/ascension/services/caseDiscussionService.js, app/ascension/views/caseDiscussion.jade, app/ascension/views/caseView.jade, app/chromed.html, app/common/services/udsService.js, app/index.html, test/spec/cases/cases.controllers.test.js
@ardasgup @pbathia Please review. I have much more work to do in this but i am creating a PR to avoid merge conflicts as these are very common files.
=> Initial commit which also has the change for test case commenting

app/cases/controllers/filterSelect.js, app/cases/controllers/list.js, app/cases/controllers/listFilter.js, app/cases/services/caseService.js, app/cases/services/searchCaseService.js, app/cases/views/filterSelect.jade, app/cases/views/listFilter.jade, app/chromed.html, app/common/services/constantsService.js, app/index.html
Reverts redhataccess/redhat_access_angular_ui#281
=> Revert "Revert "Changes for PCM-342""

app/ascension/views/breachStatus.jade, app/ascension/views/caseFlags.jade, app/ascension/views/caseView.jade, app/ascension/views/searchSolutions.jade, app/ascension/views/yourCases.jade, app/assets/sass/elements/_base.scss, app/assets/sass/includes/_helpers.scss, app/search/views/searchStackedSolutions.jade
@ardasgup @renujhamtani @pbathia
=> remove the unnecessary

app/ascension/ascension.module.js, app/ascension/controllers/accountInformation.js, app/ascension/controllers/breachStatus.js, app/ascension/services/accountService.js, app/ascension/services/caseDetailsService.js, app/ascension/views/accountInformation.jade, app/ascension/views/breachStatus.jade, app/ascension/views/entitlementInformation.jade, app/common/services/udsService.js
@ardasgup @sshumake Please review and merge
=> Changes for PCM-559 and PCM-579

app/common/views/header.jade
@pbathia @sshumake Please review and merge.
=> PCM-1017 changes

app/assets/sass/components/_recommendations.scss, app/assets/sass/elements/_base.scss, app/cases/views/addCommentSection.jade, app/cases/views/attachLocalFile.jade, app/cases/views/confirmCaseCloseModal.jade, app/cases/views/confirmCaseSeverityChangeModal.jade, app/cases/views/confirmCaseStateChangeModal.jade, app/cases/views/discussionSection.jade, app/cases/views/editCaseRecommendationsSection.jade, app/cases/views/emailNotifySelect.jade, app/cases/views/newAlternate.jade, app/cases/views/newBase.jade, app/cases/views/newCaseRecommendationsAlternateSection.jade, app/cases/views/newCaseRecommendationsSection.jade, app/cases/views/proceedWithoutAttachModal.jade
@mattnolting Is there a list of the issues that fixed(did this come from an etherpad)?  Id like something for test to verify.
@ardasgup @pbathia @renujhamtani - Please review.  I will merge when I get a Jira tracking the fixes.
=> fix various spacing issues / pagination / update button class & styling

app/ascension/controllers/caseDiscussion.js, app/cases/controllers/discussionSection.js
=> PCM-958 changes

app/cases/views/list.jade
@pbathia @ardasgup Please review
=> PCM-1011 changes

app/ascension/views/caseDiscussion.jade, app/assets/sass/components/_case-list.scss, app/cases/views/discussionSection.jade, app/cases/views/filterSelect.jade, app/cases/views/list.jade
@pbathia @sshumake Please review and merge.
=> PCM-956 changes

app/i18n/template-jp.po
@sshumake Please merge this. I know we need a JIRA for this from BZ 1228018... But the Japanese need to verify the contents on some server. I will give them the CI server link to verify the japanese contents . If they dont like it, we can revert this PR.
=> Translation for japanese check

app/common/services/udsService.js
@sshumake @pbathia @ardasgup Please review this
=> Use Promise PCM-563 changes

app/cases/views/newAlternate.jade
@ardasgup @renujhamtani @pbathia
=> stray testing

app/ascension/services/accountService.js, app/ascension/views/caseDetails.jade, app/common/services/udsService.js
@ardasgup @sshumake Please review and merge.In this PR,I have just exposed the case resolution. Also while debugging this, got an error for business hours for accounts where busines hours are not defined. So added that condition too.
=> Resolution changes

app/ascension/controllers/caseDetails.js, app/ascension/controllers/caseView.js, app/ascension/services/caseDetailsService.js, app/ascension/views/caseDetails.jade, app/ascension/views/caseFlags.jade, app/ascension/views/caseView.jade, app/common/services/udsService.js
@sshumake  @renujhamtani  please review and merge !
=> Fix for PCM-1032

app/ascension/services/caseDetailsService.js, app/ascension/views/accountInformation.jade, app/ascension/views/entitlementInformation.jade, app/common/services/udsService.js
@ardasgup @sshumake Please review and merge. These contain the openCase Count changes which Adam pushed to UDS yesterday and also the SBT state changes.
=> Open Case Count and SBT state changes

app/cases/services/searchCaseService.js
@sshumake @renujhamtani pls review and merge!
=> Fix for PCM-770

bower.json
=> version bump

app/ascension/controllers/caseHistory.js, app/ascension/controllers/caseView.js, app/ascension/services/caseDetailsService.js, app/ascension/views/caseHistory.jade, app/ascension/views/caseView.jade, app/common/services/udsService.js, test/mocks/mockUDSService.js, test/spec/ascension/ascension.services.test.js
@renujhamtani @pbathia please review and merge!
=> Fix for PCM-572

app/ascension/services/caseDetailsService.js, app/ascension/views/breachStatus.jade, app/common/services/udsService.js
@ardasgup @sshumake  please review and merge. This is for display of NEP fields in ascension.
=> NEP display fields

app/ascension/views/caseDescription.jade
=> PCM-1057 changes

app/cases/services/caseService.js, app/cases/views/descriptionSection.jade
@renujhamtani @sshumake pls review and merge!
=> Fix for PCM-1084

bower.json
@sshumake  I am removing this as this is giving error on CI job, QA job in jenkins... I am nost ure where this is used. So i am not tagging this to QA today. But atleast we can merge CI request till then and check on CI
=> removing the ie shiv as it is giving 404

app/ascension/views/caseView.jade
@ardasgup @pbathia Please review and merge. I have done this according to the old mokups till yesterday.
=> PCM-1039 changes first pass

app/cases/views/list.jade
@renujhamtani @ardasgup  Please review
=> Fix or PCM-953

app/chromed.html
@renujhamtani am merging this as review not needed.
=> Removing the unwanted files from chromed html

app/cases/services/caseService.js, test/mocks/mockStrataService.js, test/spec/cases/cases.services.test.js
@renujhamtani @spenser please review !
=> Fix for PCM-1101

app/ascension/controllers/accountInformation.js, app/ascension/views/accountInformation.jade, app/ascension/views/caseDiscussion.jade
@pbathia @ardasgup Please review. These contain the changes for "Account notes deletion" as its not in this sprint and was half baked and giving errors. The other changes are to the case discussion section to show the correct dates and names after Spenser changes. Still the sorting is not working. Hope Spenser would figure this out or I would if i get time.
=> Fixes on case discussion and account note deletion

app/ascension/controllers/caseDetails.js, app/ascension/views/caseDetails.jade
@renujhamtani  @pbathia  pls review and merge !
=> Fix for PCM-1106

app/ascension/controllers/addComments.js, app/ascension/controllers/caseDiscussion.js, app/ascension/services/caseDetailsService.js, app/ascension/services/caseDiscussionService.js, app/ascension/views/accountInformation.jade, app/ascension/views/addCommentSection.jade, app/ascension/views/breachStatus.jade, app/ascension/views/caseDiscussion.jade, app/ascension/views/caseView.jade, app/common/services/udsService.js
@pbathia @ardasgup Please review and merge.
=> Defect fixing for case discussion and problem statement

app/ascension/controllers/caseView.js, app/ascension/services/caseDetailsService.js, app/ascension/views/caseView.jade, app/assets/sass/components/ascension/_toggle-switch.scss, app/assets/sass/main.scss, app/common/services/udsService.js
@ardasgup @renujhamtani  please review
top case sorting is still pending !!
=> Fix for PCM-1024,1035,1034

app/ascension/controllers/caseSearch.js, app/ascension/services/caseDetailsService.js
=> Fix for PCM-1105

app/ascension/services/caseDetailsService.js, app/common/services/udsService.js
=> slim-cases

app/ascension/views/caseDetails.jade, app/assets/sass/components/ascension/_case-details.scss
@renujhamtani @ardasgup @pbathia
=> case-details

app/ascension/services/searchService.js
@ardasgup @pbathia @renujhamtani
=> rec-pinning-fix

app/ascension/services/caseDetailsService.js
@ardasgup @renujhamtani @pbathia
=> case message

app/ascension/views/searchStackedSolutions.jade
@ardasgup @pbathia @renujhamtani
=> serarch fix

app/cases/controllers/addCommentSection.js, app/cases/services/caseService.js, app/chromed.html, test/spec/cases/cases.services.test.js
@ardasgup @sshumake Please review.
I have also committed chromed.html as it was giving error for '/search/directives/searchStackedSolutions.js' not found.
=> PCM-1075 changes

app/cases/services/caseService.js
=> Fix for PCM-1113

app/ascension/controllers/yourCases.js, app/ascension/services/caseDetailsService.js
@ardasgup @renujhamtani @sshumake  Please review !!
=> Fix for locking mechanism for PCM-1024,1034,1035

app/cases/views/list.jade, app/common/controllers/titleView.js
@ardasgup @avijra Please review
=> PCM-1112 changes

app/ascension/controllers/attachLocalFile.js, app/cases/controllers/attachLocalFile.js
@ardasgup @avijra Please review
=> PCM-1110 changes

bower.json
=> versioning

app/cases/views/edit.jade
=> Fix for pcm-1102

app/cases/controllers/new.js, app/cases/services/caseService.js
https://prod.foo.redhat.com:1337/chromed.html#/case/new?description=VGhpcyBob3N0IGlzIHJ1bm5pbmcgYSB2ZXJzaW9uIG9mIGJhc2ggdGhhdCBpcyBhZmZlY3RlZCBieSB0aGUgY29kZSBpbmplY3Rpb24gdnVsbmVyYWJpbGl0eSBrbm93biBhcyBTaGVsbHNob2NrCgpUaGUgcGFja2FnZSBhZmZlY3RlZCBpcyBiYXNoLTQuMS4yLTE1LmVsNl80Lng4Nl82NA&summary=%5Binsights%5D%20shellshock&b64=true
=> Get new case from query params

app/cases/views/attachLocalFile.jade
Adding id tag for automation attachment to the div element.
=> Adding id tag to the div elements

app/cases/services/caseService.js, app/cases/views/new.jade, app/i18n/template.pot
@sshumake Please review and merge. I have sent the changed template.pot changes to the translation team.
https://bugzilla.redhat.com/show_bug.cgi?id=1250329
If you get a response for this BZ to open a new ticket, please do that so if i am not around.
Once we get the translated strings, I will open a PR for merging those
=> Translation changes incorrect for a/b testing

bower.json
@sshumake I am updating the version for PCM-1000 changes.
=> Version update for PCM-1000

app/cases/controllers/detailsSection.js, app/cases/views/detailsSection.jade
@ardasgup @renujhamtani Please review changes for pcm 970.
=> changes for pcm-970

app/cases/controllers/new.js, test/spec/cases/cases.controllers.test.js
@renujhamtani @ardasgup Please review changes for pcm 690.
=> code changes for pcm-690

bower.json
Updating the common version for translation stuff
=> Updating the common version

app/cases/controllers/edit.js, bower.json
@ardasgup Please review this. These changes were done by Pranjal and was on hold because of strata bug not pushed to prod[1]. Now this bug has been pushed to prod. I have also done the translation changes required. All the dependent strata js files have been merged and tagged.
[1] https://projects.engineering.redhat.com/browse/CPSTRATA-377.
@sshumake  We would need translations for these newly introduced strings. I will created a hardening task for this too.
=> PCM-922 changes

app/cases/views/new.jade
@ardasgup @renujhamtani Please review
Note : As discussed with Swapna, no automation test case changes needed for this JIRA.
=> Code changes for PCM-1215

Gruntfile.js
@sshumake @ardasgup Please review
=> PCM-1221 changes

app/cases/views/discussionSection.jade, bower.json
=> PCM-1000 changes

app/cases/views/detailsSection.jade
Merging this as Swapna needs the id for cancel.
=> Automation id update

app/cases/controllers/attachLocalFile.js, app/cases/services/attachmentsService.js
@ardasgup @sshumake Please review. Even if these changes are made, there would be a bug on the format of last name and first name from CCM side. I will raise a BZ for this.
=> PCM-1253 changes

app/cases/views/listFilter.jade, app/index.html, bower.json
@renujhamtani @ardasgup Fixed PCM-1237, used rha-Enter directiove from common.
=> Fixed PCM-1237, used rha-Enter directiove from common

app/cases/views/listFilter.jade
@renujhamtani @ardasgup  Fixed PCM-1238
=> Fix for PCM-1238

app/assets/sass/components/_recommendations.scss, app/cases/services/recommendationsService.js
@renujhamtani @ardasgup Fixed PCM-1052, changes in RecommendationsService and CSS.
=> Fix for PCM-1052

app/cases/controllers/discussionSection.js, app/cases/services/caseService.js, app/cases/views/discussionSection.jade
@renujhamtani @sshumake  please review and merge !
=> Fix for PCM-1233

app/cases/views/discussionSection.jade
@renujhamtani @ardasgup Please review
=> Code changes for pcm 1270

app/cases/views/detailsSection.jade
@renujhamtani @sshumake Please review
=> Code changes for pcm 1256

app/cases/views/discussionSection.jade
@sshumake @vrathee-redhat Please review
=> PCM-1259 changes

app/cases/views/edit.jade
@renujhamtani @ardasgup Please review
=> Code changes for pcm 1277

app/cases/controllers/new.js, app/cases/controllers/newCaseRecommendationsSection.js, app/cases/directives/newCaseRecommendationsSection.js, app/cases/views/new.jade
=> pcm-1085 and pcm-1278

app/cases/views/new.jade
@vrathee @gandhikeyur Please review
=> PCM-1333 changes

app/cases/controllers/addCommentSection.js, app/cases/services/attachmentsService.js, app/cases/views/discussionSection.jade, test/spec/cases/cases.services.test.js
@gandhikeyur @vrathee Please review
=> PCM-556 changes

app/cases/services/attachmentsService.js, bower.json
@renujhamtani @vrathee Please review
=> Code Changes for PCM-1389. Sorting of comments is broken

app/cases/services/caseService.js
@renujhamtani @ardasgup Please review.
=> Fix for PCM-928

app/cases/views/new.jade
@renujhamtani @jtrantin Kindly Review
=> Fixed PCM-1510

Gruntfile.js, app/assets/sass/components/_case-discussion.scss, app/cases/services/caseService.js, app/cases/services/discussionService.js, app/cases/views/discussionSection.jade, app/chromed.html, app/index.html, app/loader.js, bower.json, karma.conf.js, test/mocks/mockStrataService.js, test/spec/cases/cases.services.test.js
=> Bluebird changes & PCM 1525 - showing external tracker updates in case discussion section

app/cases/views/discussionSection.jade
@renujhamtani @vrathee Please review.
=> PCM 1525 - Changed label as per Dan Fisher's update. Also showing Private label against partner only comments

app/cases/controllers/versionSelect.js
@sshumake @renujhamtani Please review
=> PCM 1583 - calling product.getversions only if product is not undefined

app/cases/services/caseService.js
@gandhikeyur @vrathee @sshumake @renujhamtani Please review.
=> Fix for PCM-1385

app/cases/controllers/new.js
@gandhikeyur @vrathee I am merging to test in prod
=> account for has not being a num

app/escalation/controllers/escalationRequest.js, app/escalation/views/partnerEscalation.jade
@gandhikeyur @vrathee  Please review.
=> PCM-1412: Allow empty case number in partner escalations

app/assets/sass/components/_case-new.scss, app/assets/sass/components/_severity-level.scss, app/assets/sass/main.scss, app/cases/controllers/severitySelect.js, app/cases/directives/severitySelect.js, app/cases/views/new.jade, app/cases/views/severitySelect.jade
https://projects.engineering.redhat.com/browse/PCM-1477
https://projects.engineering.redhat.com/browse/PCM-1480
@jtrantin - Thoughts on changes for radio buttons?  I couldnt get it working without requiring case service
@vrathee
=> Leslies changes

app/cases/services/manageGroupsService.js
@renujhamtani @gandhikeyur Please Review
=> Fix for PCM-1615

bower.json
@renujhamtani @vrathee Please review
=> PCM 1625 - changing stratajs version

app/cases/controllers/discussionSection.js, app/cases/views/discussionSection.jade
@renujhamtani @gandhikeyur Kindly review.
=> PCM-1521 , translations and discard button fix

app/cases/controllers/detailsSection.js, app/cases/views/new.jade
@gandhikeyur @renujhamtani @vrathee 
PCM-1631
PCM-1632
PCM-1633
=> various regressions

app/cases/views/new.jade
=> PCM 1635 - provided id to 24x7 fields in new case page

app/cases/views/detailsSection.jade
=> PCM 1647 - changed id for the dropdown

app/cases/controllers/manageGroupList.js, app/cases/services/manageGroupsService.js, app/cases/views/manageGroupList.jade
=> PCM 1526 - code changes

app/cases/controllers/manageGroupList.js, app/cases/services/manageGroupsService.js, app/cases/views/manageGroupUsers.jade
=> PCM 1458 - code changes

bower.json
=> PCM-1386 version bump

app/cases/controllers/detailsSection.js
@vrathee @ardasgup Please review
=> PCM 1676 - code changes

app/cases/services/caseService.js
=> PCM 1520 - code changes

app/cases/services/caseService.js
@vrathee @sshumake Please review
=> PCM-1609 changes

app/cases/views/edit.jade
@gandhikeyur @vrathee Please review
=> PCM-1641 changes

app/cases/controllers/edit.js, app/cases/controllers/list.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/loader.js, bower.json
@renujhamtani @ardasgup Please Review.
The "var breadcrumbs" changes were made because there is some existing problem in loader.js and other places due to which I was unable to run PCM on local.
=> Pcm header service

app/cases/controllers/edit.js, app/cases/controllers/list.js, app/cases/controllers/new.js, app/loader.js
@renujhamtani @gandhikeyur Please Review.
=> Breadcrumbs blocker Fix

app/cases/cases.module.js, app/cases/controllers/new.js
=> PCM 1693 - code changes

app/cases/services/recommendationsService.js, app/cases/views/editCaseRecommendationsSection.jade, app/cases/views/newCaseRecommendationsSection.jade, bower.json, test/mocks/mockStrataService.js
@renujhamtani @gandhikeyur Please review.
Note this is dependent on changes of stratajs and common module, which are not merged yet. Do not merge this until the PR's below are merged.
redhataccess/stratajs#28
redhataccess/redhat_access_angular_ui_common#47
=> PCM-1694: Switched from /rs/problems to /rs/recommendations

app/cases/services/recommendationsService.js, app/cases/views/editCaseRecommendationsSection.jade, app/cases/views/newCaseRecommendationsSection.jade, bower.json, test/mocks/mockStrataService.js
Reverts redhataccess/redhat_access_angular_ui#510
@jtrantin  @gandhikeyur  I am reverting this PR for the following reasons:
-the default length of the abstract appears to be different than rs/problems.  This could possibly blow up or A/B tests
-We need the highlighting of text implemented.
Lets discuss further in scrum tomorrow
=> Revert "PCM-1694: Switched from /rs/problems to /rs/recommendations"

app/cases/controllers/new.js
@renujhamtani Please review.
This should work for both cases : With and with out local storage cache.
=> PCM-1693 code changes

app/cases/directives/equalWidths.js
@sshumake There were a couple of things broken in the equalWidths file and that was breaking the redirect to edit case page after the case is newly created. I have done the changes, please verify as you were working on it recently.
=> PCM-1810 code changes

app/cases/views/requestEscalation.jade
@jtrantin @vrathee Please review
=> PCM-1784 code changes

app/assets/sass/components/_case-new.scss, app/assets/sass/components/_content-loading-notification.scss, app/cases/controllers/new.js, app/cases/views/new.jade
@renujhamtani @vrathee @gandhikeyur
=> Pcm 1811 PCM 1848

app/cases/services/recommendationsService.js, app/cases/views/newCaseRecommendationsSection.jade, bower.json, test/mocks/mockStrataService.js, test/spec/cases/cases.services.test.js
@sshumake @vrathee Please review.
=> PCM-1694: Migrated to /rs/recommendations

app/cases/controllers/new.js, app/cases/services/productsService.js
@renujhamtani @vrathee Please review.
=> PCM-1809: Added version check to new case page

app/cases/controllers/new.js, app/cases/views/emailNotifySelect.jade, app/cases/views/new.jade
@gandhikeyur @renujhamtani Please Review.
=> Fix for PCM-772

app/cases/views/emailNotifySelect.jade, app/cases/views/new.jade
@renujhamtani @gandhikeyur Please Review
=> Fixed PCM-1917

app/cases/controllers/new.js, app/cases/views/ownerSelect.jade
The root cause of this issue lied in the assignment of CaseService.users to $scope.usersOnAccount and angular.copy solved the matter. The other file change is just for sorting it according to full name.
@sshumake @jtrantin Please review
=> PCM-1926 code changes

app/cases/controllers/new.js, app/cases/services/caseService.js
=> PCM-1857: Added displayed recommendations to new case payload

app/assets/sass/components/_case-list.scss, app/cases/controllers/bookmarkedAccountSelect.js, app/cases/controllers/list.js, app/cases/directives/bookmarkedAccountSelect.js, app/cases/services/accountService.js, app/cases/services/caseService.js, app/cases/services/searchCaseService.js, app/cases/views/bookmarkedAccountSelect.jade, app/cases/views/list.jade, app/cases/views/listFilter.jade, app/chromed.html, app/index.html
=> PCM-1981: Added bookmarked account filter

app/cases/cases.module.js
=> PCM-2051: Added angular JS exception handler

app/assets/sass/components/_account_bookmark.scss, app/assets/sass/main.scss, app/cases/cases.module.js, app/cases/controllers/accountBookmarkHome.js, app/cases/controllers/accountSearch.js, app/cases/controllers/bookmarkAccount.js, app/cases/controllers/bookmarkedAccountSelect.js, app/cases/controllers/existingBookmarkedAccounts.js, app/cases/directives/accountSearch.js, app/cases/directives/bookmarkAccount.js, app/cases/directives/existingBookmarkedAccounts.js, app/cases/services/accountBookmarkService.js, app/cases/services/accountService.js, app/cases/views/accountBookmarkHome.jade, app/cases/views/accountSearch.jade, app/cases/views/bookmarkAccount.jade, app/cases/views/bookmarkedAccountSelect.jade, app/cases/views/existingBookmarkedAccounts.jade, app/chromed.html, app/index.html, bower.json
@renujhamtani @vrathee @gandhikeyur Please review.
=> PCM-1979: Added account bookmark page + Fix for PCM-2700

app/cases/controllers/listFilter.js, app/cases/views/listFilter.jade
=> PCM-1980: Added button navigating to account bookmark view

app/assets/sass/components/_case-new.scss, app/assets/sass/components/_edit.scss, app/cases/controllers/accountSelect.js, app/cases/services/accountBookmarkService.js, app/cases/views/accountSelect.jade, app/cases/views/edit.jade
=> PCM-1982: Added bookmark icon to case view and new case view

app/cases/services/caseService.js, test/spec/cases/cases.services.test.js
@renujhamtani @vrathee Please review.
Also added tests to test the most basic scenarios.
=> PCM-2727: Show unselected FTS for premium SEV 2

app/cases/services/caseService.js
@renujhamtani @vrathee Please review.
=> PCM-2716: Added default support level and FTS rules

bower.json
@gandhikeyur @renujhamtani Please Review
=> Fix for PCM-2781

app/cases/controllers/new.js, app/cases/services/recommendationsService.js
@vrathee @jtrantin Please review
=> PCM-2841 code changes

app/cases/views/list.jade
Reverts redhataccess/redhat_access_angular_ui#538
=> Revert "Breaking changes for automation testing"

app/cases/services/caseService.js
I am disabling the functionality as discussed in PCM-1857. Just commenting the code because we will want to re-enable it again when a full investigation on what fields should be sent is done.
=> Reverting PCM-1857

app/cases/services/caseService.js, test/spec/cases/cases.services.test.js
Reverts redhataccess/redhat_access_angular_ui#533
=> Revert "PCM-2727: Show unselected FTS for premium SEV 2"

app/ascension.html, app/build_index.html, app/chromed.html, app/gs4.html, app/index.html, app/loader.js, bower.json, karma.conf.js
@jtrantin I'm not too sure I did much here beyond ensure the dist/uds.js was being used and to upgrade jsuri, but it does work in local dev without errors.  Can you review this and see what we need to do next if anything?
I'm still not that familiar with the build.  It seems strange to declare the udsjs in the chrome.html and then also load it with the loader.js.  I commented out udsjs in the chrome.html file.  I'm not sure what the relevance of the ascension.html and index.html are or if they are even used.
=> Fixing the udsjs issues

app/cases/controllers/new.js
=> pcm-2955 removed a/b test for delayed recommendation fetching

app/cases/views/advancedSearch.jade
=> pcm-2976 code changes

app/cases/views/list.jade, app/index.html
=> pcm-2980 changes

app/cases/services/caseService.js, app/index.html
@gandhikeyur @renujhamtani @engineersamuel  Please Review.
You might need to merge these changes to the webpackized PCM branch.
PS: Its a work under review. I have commented on the JIRA https://projects.engineering.redhat.com/browse/PCM-1857 . Once Spenser gives his ack on the JIRA, we can merge this.
=> Code changes for PCM-1857 - Send recommendation while case creation

app/main.module.js
=> Fixing the redirectURL

app/chromed.ejs
Setting the pcm css type so it can be properly served to the browser.
=> Explicitly setting the type for the pcm css

bower.json, package.json
=> version bump to 1.2.0

app/chromed.ejs, app/main.module.js, webpack.config.js
Fixing chat functionality per https://projects.engineering.redhat.com/browse/PCM-3145
=> PCM-3145: restoring chat functionality

app/cases/controllers/editCaseRecommendationsSection.js
https://projects.engineering.redhat.com/browse/PCM-3140
Strangely this code was in the app for quite a long time, so maybe strata did some changes that introduced the pinning problems. Note that before applying this fix, the pinning worked sometimes, but sometimes it didn't. With this fix, the pinning works much better, I haven't been able to reproduce any of the problems.
=> PCM-3140: Fixed solution linking/pinning

.travis.yml, bower.json
https://projects.engineering.redhat.com/browse/PCM-3197
Issue fixed in 1.0.8 https://github.com/leocaseiro/angular-chosen/issues/158
=> PCM-3197: Upgrading chosen to 1.0.8 

app/escalation/escalation.module.js, app/escalation/services/escalationRequestService.js, app/main.module.js
@vrathee @gandhikeyur Please review on priority. After fixing the paths, escalations still weren't working, so I added some further fixes. I tested it locally and was able to create both Ice and Partner escalations.
https://projects.engineering.redhat.com/browse/PCM-3314
=> PCM-3314: Fixing escalations

app/assets/sass/elements/_base.scss, app/cases/cases.module.js, app/log_viewer/log_viewer.module.js, app/search/search.module.js
@vrathee @gandhikeyur @engineersamuel @renujhamtani 
https://projects.engineering.redhat.com/browse/PCM-3309
How do you feel we remove the ngAnimate module? AFAIK it is not used anywhere in the project and it only causes delays when hiding elements. I tested this change, and removing it doesn't seem to have any negative effects.
=> PCM-3309: Removing ngAnimate module

.travis.yml, app/assets/sass/elements/_base.scss, app/assets/sass/main.scss
@renujhamtani @vrathee The fix for missing X in account select, please review.
I just removed chosen.css that was included into the SASS, we already have chosen CSS provided by chromed themes. Also added top margin to make it centered.
=> Chosen CSS fixes

app/cases/services/caseService.js, app/chromed.ejs
@jtrantin @gandhikeyur Please review.
I also saw that ascension logo was visible while running PCM for some seconds while loading.. So fixed that as well..
Regarding the current fix. I feel it should have been in the old PCM as well but don't know why we never got it.
=> Fixing PCM-3359

app/cases/controllers/accountSearch.js, app/cases/controllers/new.js, app/cases/controllers/solrQueryInput.js, app/search/views/search_form.jade
https://projects.engineering.redhat.com/browse/PCM-3365
This error kept popping up for Spenser and other users. Since there is just few occurrences of trim I checked them all and fixed those that could be problem. Verified on new case view, where even I was getting the error.
=> PCM-3365: Fixing trim of undefined errors

app/cases/views/new.jade, app/cases/views/ownerSelect.jade, app/cases/views/productSelect.jade, app/cases/views/versionSelect.jade
https://projects.engineering.redhat.com/browse/PCM-3364
=> PCM-3364: Fixed last item selection with chosen

app/cases/services/caseService.js
@gandhikeyur Please review. Small change
=> Fixing console error on status change

bower.json
@jtrantin @gandhikeyur Please Review.
Need to merge strataJS before this one
https://github.com/redhataccess/stratajs/pull/40
=> PCM-3222 fix using new strata js with filter applied

app/assets/sass/components/_case_advanced_search.scss, app/cases/cases.module.js, app/cases/cases.routing.js, app/cases/controllers/advancedSearchController.js, app/cases/controllers/filterSelect.js, app/cases/controllers/searchBookmarkModal.js, app/cases/controllers/solrQueryInput.js, app/cases/services/searchBookmarkService.js, app/cases/services/solrGrammarService.js, app/cases/solrGrammar.txt, app/cases/views/advancedSearch.jade, app/cases/views/confirmationModal.jade, app/cases/views/searchBookmarkModal.jade, app/cases/views/solrQueryInput.jade, package.json
@vrathee @gandhikeyur @engineersamuel  Please review.
https://projects.engineering.redhat.com/browse/PCM-3024
https://projects.engineering.redhat.com/browse/PCM-3025
Will add some screens to the JIRA.
=> PCM-3024 + PCM-3025

app/assets/sass/components/_account_bookmark.scss, app/cases/controllers/accountSearch.js, app/cases/views/accountSearch.jade
@vrathee @gandhikeyur @engineersamuel  Please review.
https://projects.engineering.redhat.com/browse/PCM-2745
=> PCM-2745: Added DNF message to account search

app/main.module.js
https://projects.engineering.redhat.com/browse/PCM-3460
This piece was originally present in the index.html in CI gear repo, and it got deleted when we switched to webpack. Confirmed on QA env it sets the right Case Origin for new cases.
=> PCM-3460: Setting redhat_client for Strata

app/assets/sass/elements/_base.scss, app/cases/views/edit.jade
@gandhikeyur @jtrantin Please review.
https://projects.engineering.redhat.com/browse/PCM-2905
=> PCM-2905 Added hotfix and special handeling flags and corrected template for better line spacing

app/escalation/controllers/escalationRequest.js, app/escalation/services/escalationRequestService.js
Re-enabling the submit button whenever error occurs when submitting the escalation.
=> PCM-3315: Re-Enabling Escalation submit button on error

app/cases/views/advancedSearch.jade, app/cases/views/list.jade
=> PCM-3338: Hiding pagination when not needed

app/assets/sass/components/_case-discussion.scss, app/cases/views/discussionSection.jade, app/cases/views/editGroup.jade, app/cases/views/listNewAttachments.jade, app/cases/views/manageGroupUsers.jade, app/escalation/views/iceEscalation.jade, app/escalation/views/partnerEscalation.jade
Fix some jades text invalid error
=> PCM-3333 Fix post button margin issue

app/assets/sass/components/_case_advanced_search.scss, app/cases/controllers/advancedSearchController.js, app/cases/services/advancedCaseSearchService.js, app/cases/views/advancedSearch.jade, app/cases/views/confirmationModal.jade, bower.json, package.json
https://projects.engineering.redhat.com/browse/PCM-3048
=> PCM-3048: Added CSV Export to Case Search

app/cases/controllers/advancedSearchController.js, app/cases/controllers/list.js, app/cases/services/advancedCaseSearchService.js, app/cases/services/searchCaseService.js, app/cases/views/advancedSearch.jade, app/cases/views/list.jade
1. Page will start from 1
2. Fix page number is 0 error when do filter
3. Fix page number incorrect on advancedSearch
=> PCM-3331 Fix pag number incorrect issue

app/chromed.ejs, app/main.module.js
@vrathee @gandhikeyur @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-3257
I just wrapped the current auth logic in session.onInit. The current auth logic is good and will keep working even with keycloak, we just need to wait until session.js does its thing.
=> PCM-3257: Added session.js

app/cases/controllers/detailsSection.js, app/cases/views/detailsSection.jade
@jtrantin @renujhamtani Please Review
https://projects.engineering.redhat.com/browse/PCM-3226
=> PCM-3226 Kept only case description inside view more/less

app/cases/controllers/advancedSearchController.js, app/cases/views/advancedSearch.jade
https://projects.engineering.redhat.com/browse/PCM-3610
=> PCM-3610: Fixing duplicated cases + wrong offset

app/cases/views/list.jade
=> PCM-3678 fix

app/cases/controllers/edit.js, app/cases/controllers/list.js, app/cases/services/searchCaseService.js, app/cases/views/edit.jade, app/cases/views/list.jade
@jtrantin @renujhamtani @gandhikeyur Please Review.
https://projects.engineering.redhat.com/browse/PCM-3692
https://projects.engineering.redhat.com/browse/PCM-3641
It also fixes the problem when no cases found is shown on first 404 error.
=> PCM-3692 and PCM-3641 Show Spinner on Case List and Case View page

app/assets/sass/components/_case-discussion.scss, app/assets/sass/components/_case-new.scss, app/cases/controllers/attachLocalFile.js, app/cases/services/attachmentsService.js, app/cases/views/listNewAttachments.jade, app/cases/views/new.jade, bower.json, package.json, test/spec/cases/cases.services.test.js
https://projects.engineering.redhat.com/browse/PCM-2957
https://projects.engineering.redhat.com/browse/PCM-3162
This consists of two separate features. First is to show more human-friendly error if user tries to upload file he has no permission for. Now the browser tries to read first few bytes of the file to check if it can actually be uploaded.
The second is showing a progress-bar when uploading the attachments.
=> PCM-2957 + PCM-3162: Attachment uploading improvements

README.md
@renujhamtani Adding translations to the readme, so we don't forget how it's done now. Since it's just readme file I am merging without review.
=> Adding Translations to README

app/cases/views/addCommentSection.jade, app/cases/views/advancedSearch.jade, app/cases/views/attachLocalFile.jade, app/cases/views/commonConfirmationModal.jade, app/cases/views/detailsSection.jade, app/cases/views/discussionSection.jade, app/cases/views/list.jade, app/cases/views/listFilter.jade, app/cases/views/manageGroupList.jade, app/cases/views/new.jade, app/cases/views/proceedWithoutAttachModal.jade, app/cases/views/requestEscalation.jade, app/cases/views/searchBox.jade
@jtrantin @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-3784 
Thing to note:
I have added ".btn-primary" to those buttons that were always enabled.
However, if we added ".btn-primary" to buttons that get disabled conditionally, they appeared to be of light blue color, which is not desirable. Hence, I applied ".btn-primary" condition using ng-class only when the buttons are enabled.
=> PCM-3784 code changes

app/cases/controllers/discussionSection.js, app/cases/views/new.jade
@gandhikeyur @renujhamtani Please review.
Note there is some weirdness in how strata is handling attachments in new cases (which also causes PCM-3769), so if you test something, make sure to test it on an older case. I will create strata jiras.
https://projects.engineering.redhat.com/browse/PCM-3752
=> PCM-3752: Removed duplicate file upload in New view

app/cases/constants/caseEvents.js, app/cases/controllers/advancedSearchController.js, app/cases/controllers/filterSelect.js, app/main.module.js, package.json
https://projects.engineering.redhat.com/browse/PCM-3818
This was mostly caused by the session.js-related changes in securityService. Fix for that is already common module, while testing I found some other problems, so I fixed those too.
=> PCM-3818: Fixing Advanced Search init-related regressions

app/cases/controllers/detailsSection.js, app/cases/controllers/new.js, app/cases/directives/typeSelect.js, app/cases/services/caseService.js, app/cases/views/detailsSection.jade, app/cases/views/new.jade, app/cases/views/productSelect.jade, app/cases/views/typeSelect.jade, test/spec/cases/cases.services.test.js
@gandhikeyur @jtrantin Please Review.
=> PCM-3680 Added case type field, KT Questions and made it mandatory

app/assets/sass/components/_case-discussion.scss, app/cases/controllers/addCommentSection.js, app/cases/controllers/emailNotifySelect.js, app/cases/directives/emailNotifySelect.js, app/cases/services/caseService.js, app/cases/views/edit.jade, app/cases/views/emailNotifySelect.jade, test/spec/cases/cases.controllers.test.js, test/spec/cases/cases.services.test.js
https://projects.engineering.redhat.com/browse/PCM-3837
Photo with basic description can be found in the jira.
=> PCM-3837: Adding internal user watchers

app/assets/sass/components/_case-discussion.scss, app/cases/controllers/addCommentSection.js, app/cases/controllers/emailNotifySelect.js, app/cases/directives/emailNotifySelect.js, app/cases/services/caseService.js, app/cases/views/edit.jade, app/cases/views/emailNotifySelect.jade, test/spec/cases/cases.controllers.test.js, test/spec/cases/cases.services.test.js
https://projects.engineering.redhat.com/browse/PCM-3826
Note this is based on PCM-3837, so when you review just open the latest commit related to PCM-3862.
=> PCM-3862: Fixing repeated values in user selects

app/cases/controllers/emailNotifySelect.js
As per the latest comment in https://projects.engineering.redhat.com/browse/PCM-3837, we are fetching the user info to get the `is_internal` flag. This is a short term fix, ultimately we'll want to add that flag into the account/users response.
=> PCM-3837: Checking if watcher is internal before adding him

app/assets/sass/components/_list-group.scss, app/cases/controllers/manageGroupList.js, app/cases/views/manageGroupList.jade
https://projects.engineering.redhat.com/browse/PCM-3843
Group name should be non-empty and unique, otherwise disable the submit btn. Also did some tweaks on the UI.
=> PCM-3843: Making group name mandatory and unique

app/cases/services/caseService.js, package.json
@engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-4142
The second part of the fix for PCM-4142. Theoretically, we don't need to add the empty-check, since it works fine with only the common changes. But I feel much better having two separate fixes in place :)
=> PCM-4142: Fixing empty entitlements issue

app/cases/controllers/new.js
@renujhamtani @jtrantin Small change.. To show KT questions on new case type..
https://projects.engineering.redhat.com/browse/PCM-3998
=> PCM-3998 Fix, added new case type to KT question array

app/assets/sass/components/_pinned.scss, app/assets/sass/components/_recommendations.scss, app/assets/sass/elements/_lists.scss, app/cases/controllers/editCaseRecommendationsSection.js
@engineersamuel @vrathee @gandhikeyur Please review.
https://projects.engineering.redhat.com/browse/PCM-3622
=> PCM-3622: Showing Pin always + Expanding Handpicked

package.json
@jtrantin @renujhamtani Please review and merge once commons has been tagged
=> Bumping commons version in PCM

app/cases/controllers/accountSelect.js, app/cases/controllers/detailsSection.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/detailsSection.jade, app/cases/views/new.jade, test/mocks/mockStrataService.js, test/spec/cases/cases.controllers.test.js
@renujhamtani @jtrantin Please review.. Attached screen shots in the JIRA.
We can wait for confirmation of the desired functionality from stakeholders on the JIRA before merging this.. But this is good to go for code review.
https://projects.engineering.redhat.com/browse/PCM-3308
=> Pcm 3308 Added enhanced SLA flag on create and edit case page

app/cases/controllers/emailNotifySelect.js, app/cases/views/emailNotifySelect.jade
@vrathee @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-4382
=> PCM-4382: Fixing watcher button for case contacts

app/assets/sass/elements/_base.scss, app/cases/cases.module.js, app/cases/components/managedAccountSelect.js, app/cases/controllers/accountSelect.js, app/cases/controllers/bookmarkedAccountSelect.js, app/cases/controllers/detailsSection.js, app/cases/controllers/listFilter.js, app/cases/controllers/managedAccountSelect.js, app/cases/services/caseService.js, app/cases/services/searchCaseService.js, app/cases/views/accountSelect.jade, app/cases/views/detailsSection.jade, app/cases/views/list.jade, app/cases/views/listFilter.jade, app/cases/views/managedAccountSelect.jade, bower.json, package.json
@jtrantin @renujhamtani Please Review
Attached screenshots in JIRA
https://projects.engineering.redhat.com/browse/PCM-4334
https://projects.engineering.redhat.com/browse/PCM-4303
=> PCM-4334 Added managed account Filter on case list and case creation page

app/cases/views/managedAccountSelect.jade
@renujhamtani Please review.. The actual account list comes in a accounts object.. thus had to update accordingly..
=> Updating datasource for managedaccounts

package.json
@renujhamtani  Please review and merge
seems there was a new tag published for moment-timezone that broke the build.. 
https://github.com/moment/moment/blob/develop/CHANGELOG.md
=> Using specific version of moment-timezone

app/cases/controllers/bookmarkedAccountSelect.js, app/cases/services/accountBookmarkService.js
=> PCM-4395: Fixing Bookmark-Managed accounts interaction

app/cases/components/managedAccountSelect.js, app/cases/controllers/list.js, app/cases/controllers/listFilter.js, app/cases/services/caseService.js, app/cases/services/searchCaseService.js, app/cases/views/list.jade, app/cases/views/listFilter.jade, test/mocks/mockStrataService.js, test/spec/cases/cases.controllers.test.js
- searchText
- caseGroup
- caseStatus
- bookmarkAccount
All filters can be stored in localStorage
removed unuse code
=> PCM-4333 Store the search filter in localStorage

app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/detailsSection.jade, app/cases/views/new.jade
@jtrantin @renujhamtani Please review.
=> PCM-3493: hide the hostname to internal users, and add it to localstorage cache

app/cases/controllers/discussionSection.js
@jtrantin @renujhamtani Please review.
=> PCM-4181: fix the bug that Discard change not working for Private Note

app/cases/services/caseService.js
@jtrantin @renujhamtani Please review.
=> fix the bug that hostname cannot be edited in case view

app/cases/controllers/detailsSection.js, app/cases/controllers/discussionSection.js, package.json
@gandhikeyur @renujhamtani Please review.
Note this is waiting on common PR. Do not merge until that is merged and published.
=> PCM-4485: Clearing all case search caches on case update

app/cases/controllers/addCommentSection.js, app/cases/controllers/commonConfirmationModal.js, package.json
=> PCM-4485: Clearing search on few more case updates

app/cases/controllers/edit.js, app/cases/views/edit.jade
@gandhikeyur @renujhamtani  Please review.
https://projects.engineering.redhat.com/browse/PCM-4498
=> PCM-4498: Showing account info for externals with managed accounts

app/cases/services/productsService.js
@gandhikeyur @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-4497
=> PCM-4497: Fetching products from case owner for external partners

app/cases/services/searchCaseService.js
@gandhikeyur @renujhamtani  Please review
=> Fixed case list, internal user issue

app/cases/controllers/new.js, app/cases/views/new.jade
@renujhamtani @gandhikeyur Please review
=> Pcm 4503 and PCM-4507 Fixes related to account number select and enhanced SLA on create case page

app/cases/controllers/accountSelect.js, app/cases/controllers/edit.js, app/cases/controllers/list.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/services/productsService.js, app/cases/views/new.jade, app/cases/views/ownerSelect.jade, app/cases/views/productSelect.jade
@renujhamtani @gandhikeyur Please review
https://projects.engineering.redhat.com/browse/PCM-4509
https://projects.engineering.redhat.com/browse/PCM-4515
https://projects.engineering.redhat.com/browse/PCM-4512
https://projects.engineering.redhat.com/browse/PCM-4508
https://projects.engineering.redhat.com/browse/PCM-4510
https://projects.engineering.redhat.com/browse/PCM-3468 => removed Portal case management form title on edit case page.
=> Fixed various issues on case create page

app/cases/controllers/emailNotifySelect.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/bookmarkedAccountSelect.jade, app/cases/views/emailNotifySelect.jade, app/cases/views/manageGroupList.jade, app/cases/views/managedAccountSelect.jade, package.json
@vrathee @kunyan Please review
https://projects.engineering.redhat.com/browse/PCM-4511
https://projects.engineering.redhat.com/browse/PCM-4391
https://projects.engineering.redhat.com/browse/PCM-4478
https://projects.engineering.redhat.com/browse/PCM-4476
Note : This PR is dependent on https://github.com/redhataccess/redhat_access_pcm_ascension_common/pull/46
=> Pcm 4511 & PCM 4391 & PCM 4478 & PCM 4476 Code changes

app/cases/controllers/detailsSection.js, app/cases/controllers/new.js, app/cases/views/edit.jade, app/cases/views/new.jade
@vrathee @renujhamtani Please review. Blocker fix.
Also added another check for not showing bookmark account icon to non internal users.
https://projects.engineering.redhat.com/browse/PCM-4566
=> pcm-4566 code changes

app/assets/sass/elements/_base.scss, app/cases/controllers/accountBookmarkHome.js, app/cases/controllers/accountSelect.js, app/cases/views/accountBookmarkHome.jade, app/cases/views/accountSelect.jade, app/cases/views/detailsSection.jade, app/cases/views/edit.jade, app/main.module.js
=> Secure Support : Hiding RME and other minor changes

app/cases/controllers/detailsSection.js, app/cases/views/accountSelect.jade, app/cases/views/detailsSection.jade
Merging this as these are minor changes.
https://projects.engineering.redhat.com/browse/PCM-4606 
https://projects.engineering.redhat.com/browse/PCM-4608
=> PCM-4606 & PCM-4608 code changes

app/cases/controllers/detailsSection.js, app/cases/views/detailsSection.jade
@renujhamtani @vrathee Adding a missing condition for showing sbr and moving the showSbr criteria in the controller. Small change. Merging this.
=> PCM-4608 code changes

app/cases/views/manageGroups.jade
@vrathee @renujhamtani Adding secure support banner on top of manage case groups page. Merging this.
=> PCM-4626 banner on manage case groups page

app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/new.jade
https://projects.engineering.redhat.com/browse/PCM-4668
=> PCM-4668 : Recommendations fetch code changes

app/cases/services/caseService.js, app/cases/views/detailsSection.jade, app/cases/views/edit.jade, bower.json, package.json, test/spec/cases/cases.services.test.js
@vrathee @engineersamuel Please review.
Internal secure support associates need to be able to changes case owner and update sbr groups via PCM. These changes are related to that.
=> PCM-4460 code changes

app/cases/controllers/editCaseRecommendationsSection.js
@vrathee @kunyan Please review.
https://projects.engineering.redhat.com/browse/PCM-4300 
Sending the resource_uri & resource_view_uri if available while pinning/unpinning the knowledge resource in a case using strata.
=> PCM-4300 code changes

app/cases/views/edit.jade
@vrathee @engineersamuel  @renujhamtani Please review.
The col-md was interfering with the above applied col-sm on the divs.
Just had to fix this to col-sm to the aside of the recommedations and the RME and the issue gets fixed.
https://projects.engineering.redhat.com/browse/PCM-4675
=> PCM-4675 code changes

app/cases/constants/status.js, app/cases/services/searchCaseService.js, bower.json, package.json
@vrathee @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-4137 
Note:
This PR is dependent on changes in https://github.com/redhataccess/stratajs/pull/50 & https://github.com/redhataccess/redhat_access_pcm_ascension_common/pull/48
=> PCM-4137 code changes

app/cases/controllers/changeOwnerModal.js, app/cases/views/changeOwnerModal.jade
@vrathee @renujhamtani Please review. I am merging this as this is needed for secure support.
Will implement review suggestions, if any, in upcoming PRs.
=> Changes to show new case owner upon successful case owner update

app/cases/controllers/changeOwnerModal.js, app/cases/views/changeOwnerModal.jade
@vrathee @renujhamtani Please review. 
https://projects.engineering.redhat.com/browse/PCM-4969 
https://projects.engineering.redhat.com/browse/PCM-4970
=> pcm-4969 and pcm-4970 code changes

app/cases/controllers/detailsSection.js, app/cases/views/detailsSection.jade
As dicussed with @renujhamtani , I am re-enabling all the update SBR changes need in PCM for secure support. merging this PR as it is needed asap.
=> Enabling secure support sbr related changes

app/cases/views/discussionSection.jade
@engineersamuel @kunyan @vrathee  Please review.
https://projects.engineering.redhat.com/browse/PCM-5351
=> PCM 5351 increasing action plan character limit

app/cases/views/secureSupportHeader.jade
@engineersamuel @kunyan @vrathee Please review.
https://projects.engineering.redhat.com/browse/PCM-5362
=> PCM 5362 increasing action plan character limit

app/cases/controllers/new.js, app/cases/services/caseService.js, bower.json, package.json
@renujhamtani @vrathee @engineersamuel @kunyan Please review.
https://projects.engineering.redhat.com/browse/PCM-5350
=> Pcm 5350 : sending the new case number to solution engine

app/cases/controllers/new.js, app/cases/services/caseService.js
@renujhamtani Merging this as need to test this on QA.
=> PCM 5052 accessing object from window localStorage

app/cases/views/list.jade
@renujhamtani @engineersamuel @kunyan Please review.
https://projects.engineering.redhat.com/browse/PCM-5159 
Merging this as this is a simple change, do let me know if anyone feels otherwise.
=> PCM 5159 adding solution engine URL in PCM

app/cases/views/list.jade
@renujhamtani Merging this, just changed the wordings.
=> Pcm 5159 wording changes

app/cases/views/list.jade
@renujhamtani @engineersamuel @kunyan Please review.
As per the comment by Tom Butt in PCM-5159, hiding this message until we receive an ack from Solution Engine stakeholders.
https://projects.engineering.redhat.com/browse/PCM-5159
=> PCM 5159 hiding solution engine message on case list page

app/assets/sass/components/_case-discussion.scss, app/cases/controllers/emailNotifySelect.js, app/cases/views/emailNotifySelect.jade
@renujhamtani @vrathee @engineersamuel @kunyan Please review.
Merging this as this is just a small styling change. Please comment if you feel otherwise.
https://projects.engineering.redhat.com/browse/PCM-5475
=> PCM 5475 code changes for email notification field for external/internal non org admins on a case with no email notify contacts

app/cases/controllers/new.js
@renujhamtani @engineersamuel @kunyan Please review.
https://projects.engineering.redhat.com/browse/PCM-5482
=> PCM 5482 awaiting adding of all notified users

app/cases/services/recommendationsService.js, bower.json
@engineersamuel @renujhamtani @anujsi Please review.
https://projects.engineering.redhat.com/browse/PCM-5386
=> PCM 5386 Fetching all recommendation types

app/cases/controllers/emailNotifySelect.js, app/cases/views/emailNotifySelect.jade
@renujhamtani @engineersamuel @kunyan @anujsi Please review
https://projects.engineering.redhat.com/browse/PCM-5554
=> PCM-5554:Ability to add/delete external non org admin as a watcher to a case

app/cases/controllers/emailNotifySelect.js, app/cases/controllers/productSelect.js, app/cases/services/caseService.js, app/cases/views/discussionSection.jade, app/cases/views/emailNotifySelect.jade
@kunyan @vrathee @anujsi @renujhamtani @engineersamuel  Please review.
https://projects.engineering.redhat.com/browse/PCM-5478
=> Pcm 5478 : Premium plus service level changes in new and edit case pages

bower.json
@renujhamtani @engineersamuel Please review. just bumping stratajs.
https://projects.engineering.redhat.com/browse/PCM-5386
=> PCM-5386 : bumping stratajs version to not fetch documenatation doctype for recommendations

app/cases/services/caseService.js
@renujhamtani @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-5478
=> PCM-5478 : making PCM failsafe to work with PREMIUMPLUS or PREMIUM PLUS

app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/services/productsService.js
@engineersamuel @renujhamtani @anujsi @kunyan Please review.
https://projects.engineering.redhat.com/browse/PCM-5264
=> PCM-5264 : Partner Case Management changes in new case creation

app/cases/views/emailNotifySelect.jade
@engineersamuel @kunyan @anujsi @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-5650
=> PCM-5650:External non-org admin case contact can't remove me as watcher

app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/services/productsService.js
@engineersamuel @renujhamtani Please review.
Commented all the changes done in https://github.com/redhataccess/redhat_access_angular_ui/pull/697/files as per the comment by Renu in https://projects.engineering.redhat.com/browse/PCM-5264
=> PCM-5264 : Reverting Partner case mgmt changes

app/cases/services/caseService.js
@engineersamuel @renujhamtani @kunyan @anujsi Please review.
https://projects.engineering.redhat.com/browse/PCM-5667
=> PCM-5667 : FTS flag changes for Premium plus entitlement case

app/chromed.ejs, app/index.html, app/main.module.js
@engineersamuel @renujhamtani @anujsi Please review.
https://projects.engineering.redhat.com/browse/PCM-5652
=> PCM-5652 : Liveagent code changes post stage refresh

app/cases/views/list.jade, app/main.module.js, package.json
@engineersamuel @renujhamtani @anujsi Please review.
https://projects.engineering.redhat.com/browse/PCM-5665 
This is dependent on commons PR https://github.com/redhataccess/redhat_access_pcm_ascension_common/pull/51/files
=> PCM-5665 : resolving infinte loop on invalid subscription error

app/cases/views/list.jade, app/main.module.js
@engineersamuel @renujhamtani @anujsi Please review. Blocker fix.
https://projects.engineering.redhat.com/browse/PCM-5681 
https://projects.engineering.redhat.com/browse/PCM-5675
=> PCM-5681 & PCM-5675 code changes

app/cases/services/caseService.js
=> hydra call comment from pcm.

app/cases/services/caseService.js, app/cases/views/discussionSection.jade, app/shared/hydra.js
@engineersamuel @renujhamtani @kunyan Please review.
https://projects.engineering.redhat.com/browse/PCM-4449
=> PCM-4449: Enabled comment feedback & used external Hydra Comment feedback API

app/cases/controllers/addCommentSection.js, test/spec/cases/cases.controllers.test.js
@renujhamtani @engineersamuel @kunyan Please review.
As discussed in the comments on https://projects.engineering.redhat.com/browse/PCM-5744, refetching JWT token via window.sessionJS.updateToken(true) before attachment upload in PCM.
=> PCM-5744:Updating JWT Token before uplaod attachments call

app/cases/services/caseService.js
@gandhikeyur @engineersamuel @renujhamtani @asonawan Please review.
https://projects.engineering.redhat.com/browse/PCM-5788 https://projects.engineering.redhat.com/browse/PCM-5798
=> pcm-5788 && pcm-5798 - thumbs up/down related issue.

app/cases/services/caseService.js, app/shared/hydra.js
@renujhamtani @engineersamuel @gandhikeyur @asonawan Please review.
https://projects.engineering.redhat.com/browse/PCM-5802
=> pcm-5802 - fix server error for  thumbs up/down issue .

app/assets/sass/components/_case-discussion.scss
@renujhamtani @engineersamuel @anujsi Please review. Minor css change needed for send email notification field
https://projects.engineering.redhat.com/browse/PCM-5837
=> pcm-5837 code change

app/cases/services/searchCaseService.js, bower.json, package.json
https://projects.engineering.redhat.com/browse/PCM-5905
=> pcm-5905 : case list does not show page .

app/cases/services/caseService.js
https://projects.engineering.redhat.com/browse/PCM-5879
=> pcm-5879 : add field commentCreatedBy in case comment feedback API.

app/cases/views/list.jade
@engineersamuel @gandhikeyur @kunyan @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-5159
=> pcm-5159 : uncomment code for solution engine .

app/cases/controllers/accountSelect.js, app/cases/controllers/detailsSection.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/services/productsService.js, app/cases/views/detailsSection.jade, test/mocks/mockStrataService.js
@anujsi @renujhamtani @engineersamuel @kunyan Please review
https://projects.engineering.redhat.com/browse/PCM-5264 
https://projects.engineering.redhat.com/browse/PCM-5731
=> pcm-5264 & pcm-5731 code changes

app/cases/controllers/detailsSection.js, app/cases/views/detailsSection.jade
@anujsi Please review. Merging this as this is needed for the production push today.
=> caseContact Fix when customer non org admin views partner managed cases

app/cases/services/linkifyService.js
@engineersamuel @anujsi @kunyan Please review.
https://projects.engineering.redhat.com/browse/PCM-6168
=> pcm-6168 code changes

app/cases/services/recommendationsService.js, bower.json
@gandhikeyur @engineersamuel Please review .
https://projects.engineering.redhat.com/browse/PCM-6249
=> PCM-6249 - set valid resourcetype for create case .

app/escalation/services/escalationRequestService.js, app/escalation/views/partnerEscalation.jade
@engineersamuel  @gandhikeyur please review.
now we are using new escalation object for ICE and old escalation object for a partner. https://projects.engineering.redhat.com/browse/PCM-5590
=> PCM-5590 - move changes for partner escalation on old object .

app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/new.jade
If "require_cgroup_on_create" is returning true then user has to select a case group, othewise the submit button will remain disabled in create new case.
@gandhikeyur @anujsi @kunyan please review
=> PCM-3841 Make selecting a case group required at the time of case open

app/escalation/services/escalationRequestService.js, app/escalation/views/partnerEscalation.jade
@gandhikeyur @engineersamuel please review.
https://projects.engineering.redhat.com/browse/PCM-5590
=> PCM-5590 - partner escalation point to new object .

app/cases/services/productsService.js, app/cases/views/productSelect.jade, test/mocks/mockStrataService.js, test/spec/cases/cases.services.test.js
@gandhikeyur @engineersamuel @aksgupta14 
https://projects.engineering.redhat.com/browse/PCM-5796
=> PCM-5796 - made changes in product list for supported and unsupported .

app/cases/views/new.jade, app/i18n/template-fr.po, app/i18n/template.pot
https://projects.engineering.redhat.com/browse/PCM-5762
=> PCM-5762 - make changes for french lang .

app/cases/controllers/new.js
Applied logic when user require case group is option and when it isn't. Especially for managed account
@gandhikeyur @anujsi @engineersamuel please review
=> PCM-6452 completed the jira with acceptance crietria

app/cases/services/productsService.js
@engineersamuel @gandhikeyur Please review .
https://projects.engineering.redhat.com/browse/PCM-5796
=> PCM-5796 - sort product list by alphabetical .

app/i18n/template-fr.po, app/i18n/template.pot
@engineersamuel @gandhikeyur @kunyan @aksgupta14 Please review.
https://projects.engineering.redhat.com/browse/PCM-6566
=> PCM-6566 - french lang changes for localization .

.openshift/server.js
Reverse proxy /support/cases/ice requests to the paas env instance.
=> Handling ice proxying

.openshift/server.js
Reverts redhataccess/redhat_access_angular_ui#733
All proxy has been setup in F5 and Akamai, won't need add them here
=> Revert "Handling ice proxying"

app/cases/views/new.jade
@anujsi @gandhikeyur @engineersamuel please review.
=> PCM-6569 Added mandatory and info icon in front of Case Group label

app/cases/controllers/accountSelect.js
@engineersamuel @kunyan @aksgupta14 @gandhikeyur Please review .
https://projects.engineering.redhat.com/browse/PCM-6616
=> PCM-6616 - deselect managed account donot reset account number .

app/cases/services/searchCaseService.js, bower.json, package.json
@kunyan @gandhikeyur @engineersamuel @aksgupta14 Please review.
https://projects.engineering.redhat.com/browse/PCM-5730
=> PCM-5730 - Partner query should search client account .

app/cases/controllers/edit.js, app/cases/services/recommendationsService.js
@gandhikeyur @kunyan Please review .
=> PCM-6809 - show flag case is managed by partner .

app/cases/controllers/edit.js, app/cases/controllers/new.js, app/cases/controllers/severitySelect.js, app/cases/services/caseService.js, app/cases/services/recommendationsService.js, app/cases/views/edit.jade, app/cases/views/new.jade, app/cases/views/severitySelect.jade, test/spec/cases/cases.controllers.test.js
@gandhikeyur @kunyan Please review .
https://projects.engineering.redhat.com/browse/PCM-6059 https://projects.engineering.redhat.com/browse/PCM-6060 https://projects.engineering.redhat.com/browse/PCM-6805
=> PCM-6060 & PCM-6059 - misleading sev listing for new case .

app/cases/views/new.jade
@anujsi @kunyan Please review
https://projects.engineering.redhat.com/browse/PCM-6396
=> pcm-6396 code changes

app/cases/controllers/productSelect.js, app/cases/services/caseService.js, app/cases/services/productsService.js, test/mocks/mockStrataService.js, test/spec/cases/cases.services.test.js
@kunyan @vrathee @anujsi Please review.
https://projects.engineering.redhat.com/browse/PCM-6621
=> PCM-6621 : code changes for product entitlement mapping

app/cases/controllers/discussionSection.js, app/cases/controllers/requestManagementEscalationModal.js, app/cases/services/caseService.js, app/cases/views/requestEscalation.jade, app/cases/views/requestManagementEscalationModal.jade, app/shared/hydrajs.js, test/spec/cases/cases.controllers.test.js
https://projects.engineering.redhat.com/browse/PCM-5591
https://projects.engineering.redhat.com/browse/PCM-6604
=> PCM-5591 - New RME creation using new escalation object.

app/cases/controllers/discussionSection.js, app/cases/controllers/requestManagementEscalationModal.js, app/cases/views/requestEscalation.jade, app/cases/views/requestManagementEscalationModal.jade, package.json
@gandhikeyur @vrathee @aksgupta14 @kunyan Please review.
=> PCM-7000 && revert back escalation changes .

app/cases/controllers/new.js, app/cases/services/productsService.js
@anujsi @kunyan @aksgupta14 @vrathee Please review, fixing a minor bug identified by skarale in 
https://projects.engineering.redhat.com/browse/PCM-6621
=> pcm-6621 bug fixes

app/cases/views/requestManagementEscalationModal.jade
https://projects.engineering.redhat.com/browse/PCM-7079
@anujsi @gandhikeyur @kunyan please review
=> PCM-7079 Escalation subject field now is limited to 254 characters

app/cases/services/productsService.js
@kunyan @anujsi Please review
https://projects.engineering.redhat.com/browse/PCM-7102
=> PCM-7102 - Fixing spinner loop error

app/cases/controllers/requestManagementEscalationModal.js, app/cases/views/edit.jade, app/cases/views/new.jade, app/cases/views/severitySelect.jade
@kunyan @anujsi Please review
https://projects.engineering.redhat.com/browse/PCM-7101
=> PCM-7101 Replace case contact to login user

app/chromed.ejs, app/shared/hydrajs.js, bower.json
@anujsi @kunyan please review.
=> PCM-7001 Adding support for sentry logging provided by sessionjs

app/cases/controllers/list.js, app/cases/services/caseService.js
@vrathee @anujsi @aksgupta14 Please review
https://projects.engineering.redhat.com/browse/PCM-5831
=> PCM-5831 : Case groups changes on case list page

app/cases/services/caseService.js, app/cases/views/detailsSection.jade, test/spec/cases/cases.services.test.js
@vrathee @anujsi @kunyan Please review
https://projects.engineering.redhat.com/browse/PCM-1731
=> PCM-1731 : Show readonly FTS flag and contact to sev1(non Premium) & sev2(any entitlement)

app/cases/controllers/showRMEEscalation.js
@vrathee @aksgupta14 Please review.
=> PCM-6605 - changes in the comment and alert message .

README.md
=> made changes in the readme file for release process .

app/cases/services/attachmentsService.js, app/cases/views/listNewAttachments.jade, app/shared/hydrajs.js
**Blocked By:** https://gitlab.cee.redhat.com/redhataccess/hydrajs/merge_requests/287
=> PCM-7333: Added progress bar for attachment uploads

app/cases/controllers/requestManagementEscalationModal.js, app/cases/views/showRMEEscalation.jade, test/spec/cases/cases.controllers.test.js
https://projects.engineering.redhat.com/browse/PCM-7233
=> PCM-7233 - Expose escalation closed dates to customers .

app/chromed.ejs
https://projects.engineering.redhat.com/browse/PCM-7061
=> PCM-7061 - Flash of unstyled content when loading Support Cases .

app/cases/controllers/attachLocalFile.js
@vrathee @anujsi @jeudy100 
Please review
https://projects.engineering.redhat.com/browse/PCM-7398
=> PCM-7398 updated function name which checks for valid s3 account before tooltip is configured

app/cases/views/listNewAttachments.jade
@vrathee @jeudy100 @anujsi Please review
https://projects.engineering.redhat.com/browse/PCM-7402
=> pcm-7402 code changes

app/cases/views/attachLocalFile.jade
@vrathee @jeudy100 @anujsi Please review
https://projects.engineering.redhat.com/browse/PCM-7401
=> pcm-7401 code changes

app/cases/views/addCommentSection.jade
@anujsi @vrathee @jeudy100 Please review
https://projects.engineering.redhat.com/browse/PCM-7404
=> PCM - 7404 code changes

app/shared/hydrajs.js
@vrathee @anujsi @jeudy100 Just updated hydrajs with the latest version pushed by Jordan.
Merging this PR.
=> updating hydrajs changes for PCM-7420

app/shared/hydrajs.js
@anujsi @gandhikeyur @vrathee please review
=> Not sending Authorization header in IE11

app/cases/controllers/requestManagementEscalationModal.js, app/cases/controllers/showRMEEscalation.js
@gandhikeyur @vrathee Please review.
=> PCM-7506 - Remove escalation flag while creating escalation from PCM .

app/cases/controllers/requestManagementEscalationModal.js, app/cases/controllers/showRMEEscalation.js
=> PCM-7506 - escalation minor changes .

app/cases/controllers/requestManagementEscalationModal.js, app/cases/controllers/showRMEEscalation.js
=> PCM-7506 - remove escalation flag from the escalation .

app/cases/views/list.jade
https://projects.engineering.redhat.com/browse/PCM-6913
@anujsi @gandhikeyur @vrathee @asonawan please review.
=> PCM-6913 Added case group

app/shared/hydrajs.js
=> added region in the s3 config .

app/shared/hydrajs.js
=> update hydrajs file .

app/shared/hydrajs.js, package.json
=> update hydrajs for region and url .

app/shared/hydrajs.js
@vrathee @gandhikeyur Please review .
=> update hydrajs for bookmarkaccount .

app/cases/controllers/commonConfirmationModal.js, app/cases/views/edit.jade
=> fix issue for cep flag .

app/cases/controllers/cepModal.js, app/cases/controllers/commonConfirmationModal.js, app/cases/controllers/edit.js, app/cases/views/cepModal.jade
=> PCM-7319 - update cep flag as per suggestion .

app/cases/constants/caseEvents.js, app/cases/controllers/cepModal.js, app/cases/controllers/commonConfirmationModal.js, app/cases/controllers/edit.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/cepModal.jade, app/cases/views/new.jade
@vrathee @aksgupta14 Please review.
https://projects.engineering.redhat.com/browse/PCM-7612
=> PCM-7612 - add new cep flag in the new case create page .

app/shared/hydrajs.js
=> PCM-7592 - attachment hotfix .

app/cases/controllers/changeOwnerModal.js, app/cases/controllers/edit.js, app/cases/services/caseService.js, app/cases/views/edit.jade
https://projects.engineering.redhat.com/browse/PCM-7319
=> PCM-7319 - Internal users can view case owners contact information

package.json
=> PCM-7538 Updating the version of commons to solve 413 error

app/cases/controllers/edit.js
@aksgupta14 @vrathee Please review.
https://projects.engineering.redhat.com/browse/PCM-7636
=> PCM-7636 - cep flag wrong value set if click outside prompt window.

app/cases/controllers/new.js, app/cases/controllers/ownerSelect.js, app/cases/services/caseService.js
=> PCM-7601 - minor changes for solution engine .

package-lock.json, package.json
=> Updated commons version

package-lock.json, package.json
=> Bumping commons version

app/cases/controllers/discussionSection.js, app/cases/directives/pagination.js, app/cases/views/discussionSection.jade
Jira: https://projects.engineering.redhat.com/browse/PCM-7600  
Please review @anujsi @vrathee
=> PCM-7600: Permanent links to comment anchors don't work beyond page 1.

app/cases/services/attachmentsService.js, app/main.module.js
@anujsi @praniredhat @jeudy100 Please Review!
=> PCM-7658 Download using s3 only if account is in s3 configuration

app/cases/controllers/attachLocalFile.js, app/cases/controllers/discussionSection.js, app/cases/services/attachmentsService.js, app/cases/views/attachLocalFile.jade, app/cases/views/discussionSection.jade
@anujsi @praniredhat Please Review
=> Pcm 7658  Fix for s3 not being enabled for valid accounts

app/cases/views/new.jade
@gandhikeyur Please review
Added translate filter to KT questions eventhough we use gettextCataog on them in case service to make sure they are translated
=> PCM-7676 - Added translate filter to KT questions 

app/assets/sass/components/_case-discussion.scss, app/assets/sass/components/_pagination.scss, app/cases/cases.module.js, app/cases/controllers/discussionSection.js, app/cases/directives/convertToNumber.js, app/cases/directives/pagination.js, app/cases/directives/searchBox.js, app/cases/services/discussionService.js, app/cases/services/paginationService.js, app/cases/views/discussionSection.jade, app/cases/views/pagination.jade, app/cases/views/searchBox.jade, app/search/styles/search.css, package-lock.json, package.json, test/mocks/mockStrataService.js
@vrathee  @gandhikeyur Please review,
=> Comments improvements

app/cases/controllers/discussionSection.js, app/cases/services/linkifyService.js
[JIRA] https://projects.engineering.redhat.com/browse/PCM-2020  
Please review @ascension @vrathee @anujsi
=> [PCM-2020] Linkifies bugzilla ID and simplifies linking process

app/cases/services/caseService.js
@praniredhat Small change.. Please review..
=> Making sure we dont add a user if they don't have an sso_username

app/cases/services/attachmentsService.js
=> PCM-7754 Fixing s3 upload on IE11

app/cases/services/attachmentsService.js, app/shared/hydrajs.js
=> S3 upload fix

app/cases/services/attachmentsService.js, app/shared/hydrajs.js
@praniredhat @gandhikeyur Please review.
The s3 credentials are valid for 15 minutes and the token for 899 seconds i.e 14.98 minutes.
I was checking it for expiry 30 seconds in advance.. made it 100 to avoid a race condition.
=> PCM-7776 and PCM-7793 Making queue and part size configurable and changed the timing to force refresh token

app/cases/controllers/new.js, app/cases/views/new.jade
@vrathee @praniredhat Please review.
https://projects.engineering.redhat.com/browse/PCM-7798
=> PCM-7798 - hide CEP checkbox in the case create page .

app/cases/controllers/emailNotifySelect.js, app/cases/controllers/emailNotifySelectInternal.js, app/cases/services/attachmentsService.js, app/cases/services/caseService.js, app/shared/hydrajs.js, package-lock.json, package.json
=> Fixing PCM-7819 and updating hydrajs

app/cases/controllers/edit.js, app/shared/constants.js, app/shared/hydrajs.js, app/shared/utils.js
Plese review @ascension, @anujsi , @vrathee
=> PCM-7765: Fix user preference link

app/cases/constants/solrCaseFields.js, app/cases/constants/strataCaseFields.js, app/cases/controllers/list.js, app/cases/services/advancedCaseSearchService.js, app/cases/services/searchCaseService.js, bower.json, package.json
Please review @ascension @vrathee @anujsi
=> PCM-7771: Passes FL param to rs/cases search and export to csv

app/cases/services/attachmentsService.js, package-lock.json
=> While upload is in progress, Keep trying to refreshing Auth token after every 3 minutes if its ie11 and token is set to expire within 50 seconds.

app/cases/views/edit.jade
Please review @asonawan @vrathee
=> PCM-7190: Fixes padding on case edit

app/cases/controllers/detailsSection.js
Please review @anujsi @vrathee
=> PCM-7795: linkifies description

app/cases/controllers/new.js
Not able to find jira number. will update soon.
Please review @vrathee @anujsi
=> bug fix for product and severity 

app/assets/sass/components/_case-new.scss, app/cases/controllers/emailNotifySelectInternal.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/edit.jade, app/cases/views/emailNotifySelectInternal.jade, app/cases/views/new.jade
PCM-7901 & PCM-7902
Please review @vrathee @anujsi @rh-kgarg
=> CEP Flag & Redhat Watchers

app/cases/controllers/attachLocalFile.js
=> PCM-7964: update tooltip text

app/cases/views/edit.jade, app/cases/views/new.jade
=> PCM-7902: adds isCep feature toggle & changes position

app/cases/controllers/discussionSection.js, app/cases/services/paginationService.js, app/cases/views/discussionSection.jade, app/i18n/template-fr.po, app/i18n/template-jp.po, app/i18n/template-ko.po, app/i18n/template-zh.po
@praniredhat @gandhikeyur @vrathee @anujsi please review
=> PCM-7731 Translation for discussion section

app/cases/services/attachmentsService.js
=> refreshTokenInterval for all browsers

app/cases/controllers/discussionSection.js, app/cases/services/paginationService.js, app/cases/views/discussionSection.jade, app/i18n/template-fr.po, app/i18n/template-jp.po, app/i18n/template-ko.po, app/i18n/template-zh.po
Reverts redhataccess/redhat_access_angular_ui#894
=> Revert "PCM-7731 Translation for discussion section"

app/cases/controllers/shareCaseWithPartner.js, app/shared/TnC.js
=> PCM-8106: Before sharing case with partner, check if it's authentic redirect from TnC.

app/cases/controllers/discussionSection.js, app/cases/services/caseService.js
=> PCM-7638: Feedback fix

app/cases/controllers/discussionSection.js, app/cases/directives/pagination.js, app/cases/views/discussionSection.jade
@praniredhat @vrathee @anujsi please review
=> PCM-7691: Added one time bindings and pagination for case details performance

app/cases/services/attachmentsService.js
@vrathee @aksgupta14 please review
=> PCM-7903: default to enable s3 for all accounts

app/cases/views/discussionSection.jade
@vrathee @praniredhat  please review
=> PCM-7748: Added jump to attachment when searching in case discussion

app/cases/views/severitySelect.jade
@vrathee @praniredhat please review
=> PCM-8025: changed severity info text when creating new case

app/cases/cases.module.js, app/cases/controllers/accountSelect.js, app/cases/controllers/confirmedStatesideAccountModal.js, app/cases/controllers/new.js, app/cases/services/caseService.js, app/cases/views/confirmedStatesideAccountModal.jade
Reverts redhataccess/redhat_access_angular_ui#900
=> Revert "PCM-7729: added modal for CSS customers when opening cases"

app/cases/views/severitySelect.jade
Reverts redhataccess/redhat_access_angular_ui#903
=> Revert "PCM-8025: changed severity info text when creating new case"

app/cases/views/discussionSection.jade
Reverts redhataccess/redhat_access_angular_ui#902
=> Revert "PCM-7748: Added jump to attachment when searching in case discussion"

app/cases/services/attachmentsService.js
Reverts redhataccess/redhat_access_angular_ui#906
=> Revert "PCM-7903: default to enable s3 for all accounts"

app/cases/controllers/discussionSection.js, app/cases/directives/pagination.js, app/cases/views/discussionSection.jade
Reverts redhataccess/redhat_access_angular_ui#905
=> Revert "PCM-7691: Added one time bindings and pagination for case details performance"

app/cases/controllers/shareCaseWithPartner.js, app/cases/views/listNewAttachments.jade
Please review @anujsi  @vrathee
=> Fix bug for FF where only host is referrer & better msg for Attachment description

app/cases/views/detailsSection.jade
@vrathee @praniredhat please review
=> PCM-5543: fixed xml not showing up by not binding it to the html

app/cases/controllers/new.js, app/cases/views/new.jade, app/shared/hydrajs.js, package-lock.json, package.json
@anujsi @praniredhat Please Review
=> PCM-7979 and PCM-7984 Fix - Provide Ability to remove added RH Watcher on Case Create Page

app/cases/controllers/new.js, app/cases/views/new.jade, app/shared/hydrajs.js, bower.json, package-lock.json, package.json
=> Hotfix for RH Watcher issue

app/assets/sass/components/_case-list.scss, app/cases/views/list.jade
@anujsi @vrathee please review
=> PCM-8058: added asterisk to severity icon when it has RMEs

app/assets/sass/components/_case-list.scss, app/cases/views/list.jade
Reverts redhataccess/redhat_access_angular_ui#907
=> Revert "PCM-8058: added asterisk to severity icon when it has RMEs"

app/assets/sass/components/_case-list.scss, app/cases/views/list.jade
Copy of https://github.com/redhataccess/redhat_access_angular_ui/pull/907. Did not realize I had made the changes in the wrong a copy of my local redhat_access_angular_ui.
=> PCM-8058: added column indicating if a case has been escalated

app/cases/controllers/severitySelect.js, app/cases/services/caseService.js
Copy of https://github.com/redhataccess/redhat_access_angular_ui/pull/904. Accidentally made it on redhataccess repo.
=> PCM-8026: fixed severity selection after switching product

app/cases/controllers/list.js
@vrathee @anujsi please review
=> PCM-8117: export cases to csv now based on filter

app/cases/controllers/discussionSection.js, app/cases/views/discussionSection.jade
Reverts redhataccess/redhat_access_angular_ui#939
=> Revert "PCM-8204: fixed showing results text for attachments"

app/cases/controllers/addCommentSection.js, app/cases/views/attachLocalFile.jade
Reverts redhataccess/redhat_access_angular_ui#941
=> Revert "PCM-8206: fixed attach file button not being disabled when posting comment"

app/cases/controllers/severitySelect.js
Reverts redhataccess/redhat_access_angular_ui#942
=> Revert "PCM-8026-bugfix: fixed bug that still allowed severities to not be switched"

app/cases/views/discussionSection.jade
Reverts redhataccess/redhat_access_angular_ui#940
=> Revert "PCM-8205: fixed all attachments pagination"

app/cases/views/emailNotifySelect.jade
Reverts redhataccess/redhat_access_angular_ui#938
=> Revert "PCM-8203: fixed overlapping label and input"

app/cases/controllers/severitySelect.js
Reverts redhataccess/redhat_access_angular_ui#945
=> Revert "Revert "PCM-8026-bugfix: fixed bug that still allowed severities to not be switched""

app/cases/controllers/addCommentSection.js, app/cases/views/attachLocalFile.jade
Reverts redhataccess/redhat_access_angular_ui#944
=> Revert "Revert "PCM-8206: fixed attach file button not being disabled when posting comment""

app/cases/views/discussionSection.jade
Reverts redhataccess/redhat_access_angular_ui#946
=> Revert "Revert "PCM-8205: fixed all attachments pagination""

app/cases/controllers/discussionSection.js, app/cases/views/discussionSection.jade
Reverts redhataccess/redhat_access_angular_ui#943
=> Revert "Revert "PCM-8204: fixed showing results text for attachments""

app/cases/views/emailNotifySelect.jade
Reverts redhataccess/redhat_access_angular_ui#947
=> Revert "Revert "PCM-8203: fixed overlapping label and input""

app/cases/controllers/list.js
@anujsi please review
blocked by:
1) https://github.com/redhataccess/redhat_access_pcm_ascension_common/pull/77
2) https://github.com/redhataccess/stratajs/pull/64
=> PCM-8117: refactored export csv cases function

.gitignore, app/shared/hydrajs.js
=> Removed customerEngagementScorecard from hydrajs .

app/cases/controllers/accountSelect.js, app/cases/controllers/productSelect.js, app/cases/services/caseService.js, app/cases/services/productsService.js, app/cases/views/productSelect.jade
@anujsi please review
P.S. I asked akshay and pranjal if there should be a client side limit or if the server automatically limits the list of recently selected products. I will need to add a limit if the server doesn't automatically send a limited list.
=> PCM-7065: added recently selected products when creating a new case

app/assets/sass/components/_case-description.scss, app/assets/sass/components/_case-discussion.scss, app/assets/sass/components/_edit.scss, app/assets/sass/elements/_pre.scss, app/assets/sass/main.scss, app/cases/views/detailsSection.jade, app/cases/views/discussionSection.jade, app/cases/views/edit.jade
=> PCM-2764: fixed not copying line breaks in discussion comments

app/cases/controllers/list.js, bower.json, package.json
@jeudy100 @vrathee Please review.
https://projects.engineering.redhat.com/browse/PCM-8469
=> PCM-8469 - Advanced case search not returning expected results .

app/assets/sass/components/_case-list.scss, app/cases/constants/solrCaseFields.js, app/cases/views/list.jade
This is a WIP because I added the correct field for the case escalation, but I am still not getting the escalation on the case objects.
blocked by:
https://github.com/redhataccess/stratajs/pull/65
=> PCM-8058-bugfix: added case_customer_escalation to solr query fields constant

app/cases/services/caseService.js, app/cases/views/emailNotifySelect.jade
@anujsi @vrathee @jeudy100 Please review.
=> hide custom email feature for a managed account

app/cases/views/list.jade
@anujsi @vrathee @jeudy100 Please review.
=> use correct condition to check if case is escalated or not

app/cases/controllers/attachLocalFile.js, app/cases/services/attachmentsService.js, app/cases/views/attachLocalFile.jade, app/shared/hydrajs.js
@anujsi @jeudy100 Please review
=> pcm-8592: disable attach file btn if s3 upload is disabled

app/cases/controllers/productSelect.js, app/cases/services/productsService.js, test/mocks/mockStrataService.js, test/spec/cases/cases.controllers.test.js
=> PCM-7065: changed get products/version api to hydra

app/assets/sass/components/_alerts.scss, app/assets/sass/components/_carousel-nav.scss, app/assets/sass/components/_case-discussion.scss, app/assets/sass/components/_case-list.scss, app/assets/sass/components/_recommendations.scss, app/assets/sass/components/_table-list.scss, app/assets/sass/elements/_aside.scss, app/assets/sass/elements/_links.scss, app/assets/sass/elements/_lists.scss, app/assets/sass/elements/_typography.scss, app/assets/sass/includes/_functions.scss, app/cases/styles/case.css
=> PCM-1416: added style changes to text line-height and link font size

app/cases/views/descriptionSection.jade, package.json
@vrathee @rh-kgarg @jeudy100 Please review.
we need to do hotfix for this issue.
https://projects.engineering.redhat.com/browse/PCM-8801
The regression has come for this PR:
https://github.com/redhataccess/redhat_access_angular_ui/commit/bb5868d24cd1abdd17f1a0e85d4511f48ebb7f30#diff-735cd53e0198c50dcf30f7f75be9d6e9
=> PCM-8801 - user is not able to update severity .

app/cases/controllers/detailsSection.js, app/cases/controllers/new.js, app/cases/controllers/productSelect.js, app/cases/services/caseService.js, app/cases/services/productsService.js, app/cases/views/detailsSection.jade, app/cases/views/new.jade, test/mocks/mockStrataService.js
@vrathee @anujsi @jeudy100 Please review
Please use this url to hide whitespace changes
https://github.com/redhataccess/redhat_access_angular_ui/pull/1032/files?utf8=%E2%9C%93&diff=unified&w=1
=> add cluster id for openshift products

app/i18n/template-de.po, app/i18n/template-es.po, app/i18n/template-fr.po, app/i18n/template-it.po, app/i18n/template-jp.po, app/i18n/template-ko.po, app/i18n/template-pt.po, app/i18n/template-zh.po, app/i18n/template_ru.po
=> PCM-8542 adding translation for remote rider

app/cases/controllers/markdownEditor.js, app/cases/views/markdownEditor.jade
@rh-kgarg @vrathee Please review.
=> PCM-6822 - undo redo is not working for markdown feature .

app/assets/sass/components/_case-description.scss, app/assets/sass/components/_case-discussion.scss
@rh-kgarg @asonawan Please review.
https://projects.engineering.redhat.com/browse/PCM-8633
@asonawan 
You have fixed this issue for comment textarea but it is breaking for comment section and case description.
PR: https://github.com/redhataccess/redhat_access_angular_ui/pull/1028/files
=> PCM-8633 - fix format issue in description and comment section .

app/assets/sass/components/_case-discussion.scss
@rh-kgarg @vrathee Please review.
=> minor code changes for preview text in markdown .

app/cases/controllers/discussionSection.js, app/cases/views/discussionSection.jade
@vrathee @rh-kgarg Please review.
=> fixed minor issue for restrict download .

app/cases/services/discussionService.js, app/cases/views/addCommentSection.jade
=> Added markdown tooltip and set default as plain text .

app/assets/sass/components/_case-discussion.scss, app/cases/controllers/discussionSection.js, app/cases/controllers/markdownEditor.js, app/cases/views/discussionSection.jade, app/cases/views/markdownEditor.jade, app/shared/utils.js
@vrathee @rh-kgarg Please review.
=> fixed html/xml issue for markdown .

app/assets/sass/components/_case-discussion.scss, app/shared/utils.js
=> minor issue for showing html/xml in  markdown .

app/server.js
@vrathee @anujsi Please review.
=> serverjs changes for support-beta release

webpack.config.js
@vrathee @anujsi please review.
=> remove public path in webpack config
